// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/BenHagueNZ/msgraph.go/jsonx"
)

// IPNamedLocation returns request builder for IPNamedLocation collection rcn
func (b *NamedLocationRequestBuilder) IPNamedLocation() *NamedLocationIPNamedLocationCollectionRequestBuilder {
	bb := &NamedLocationIPNamedLocationCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/IpNamedLocation"
	return bb
}

// NamedLocationIPNamedLocationCollectionRequestBuilder is request builder for IPNamedLocation collection
type NamedLocationIPNamedLocationCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for IPNamedLocation collection
func (b *NamedLocationIPNamedLocationCollectionRequestBuilder) Request() *NamedLocationIPNamedLocationCollectionRequest {
	return &NamedLocationIPNamedLocationCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for IPNamedLocation item
func (b *NamedLocationIPNamedLocationCollectionRequestBuilder) ID(id string) *IPNamedLocationRequestBuilder {
	bb := &IPNamedLocationRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// NamedLocationIPNamedLocationCollectionRequest is request for IPNamedLocation collection
type NamedLocationIPNamedLocationCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for IPNamedLocation collection
func (r *NamedLocationIPNamedLocationCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]IPNamedLocation, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []IPNamedLocation
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []IPNamedLocation
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for IPNamedLocation collection, max N pages
func (r *NamedLocationIPNamedLocationCollectionRequest) GetN(ctx context.Context, n int) ([]IPNamedLocation, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for IPNamedLocation collection
func (r *NamedLocationIPNamedLocationCollectionRequest) Get(ctx context.Context) ([]IPNamedLocation, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for IPNamedLocation collection
func (r *NamedLocationIPNamedLocationCollectionRequest) Add(ctx context.Context, reqObj *IPNamedLocation) (resObj *IPNamedLocation, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}
