// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "encoding/json"

// ResultInfo undocumented
type ResultInfo struct {
	// Object is the base model of ResultInfo
	Object
	// Code undocumented
	Code *int `json:"code,omitempty"`
	// Message undocumented
	Message *string `json:"message,omitempty"`
	// Subcode undocumented
	Subcode *int `json:"subcode,omitempty"`
}

// ResultTemplate undocumented
type ResultTemplate struct {
	// Object is the base model of ResultTemplate
	Object
	// Body undocumented
	Body json.RawMessage `json:"body,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
}

// ResultTemplateDictionary undocumented
type ResultTemplateDictionary struct {
	// Dictionary is the base model of ResultTemplateDictionary
	Dictionary
}

// ResultTemplateOption undocumented
type ResultTemplateOption struct {
	// Object is the base model of ResultTemplateOption
	Object
	// EnableResultTemplate undocumented
	EnableResultTemplate *bool `json:"enableResultTemplate,omitempty"`
}
