// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Shared undocumented
type Shared struct {
	// Object is the base model of Shared
	Object
	// Owner undocumented
	Owner *IdentitySet `json:"owner,omitempty"`
	// Scope undocumented
	Scope *string `json:"scope,omitempty"`
	// SharedBy undocumented
	SharedBy *IdentitySet `json:"sharedBy,omitempty"`
	// SharedDateTime undocumented
	SharedDateTime *time.Time `json:"sharedDateTime,omitempty"`
}

// SharedDriveItem undocumented
type SharedDriveItem struct {
	// BaseItem is the base model of SharedDriveItem
	BaseItem
	// Owner undocumented
	Owner *IdentitySet `json:"owner,omitempty"`
	// DriveItem undocumented
	DriveItem *DriveItem `json:"driveItem,omitempty"`
	// Items undocumented
	Items []DriveItem `json:"items,omitempty"`
	// List undocumented
	List *List `json:"list,omitempty"`
	// ListItem undocumented
	ListItem *ListItem `json:"listItem,omitempty"`
	// Permission undocumented
	Permission *Permission `json:"permission,omitempty"`
	// Root undocumented
	Root *DriveItem `json:"root,omitempty"`
	// Site undocumented
	Site *Site `json:"site,omitempty"`
}

// SharedInsight undocumented
type SharedInsight struct {
	// Entity is the base model of SharedInsight
	Entity
	// LastShared undocumented
	LastShared *SharingDetail `json:"lastShared,omitempty"`
	// ResourceReference undocumented
	ResourceReference *ResourceReference `json:"resourceReference,omitempty"`
	// ResourceVisualization undocumented
	ResourceVisualization *ResourceVisualization `json:"resourceVisualization,omitempty"`
	// SharingHistory undocumented
	SharingHistory []SharingDetail `json:"sharingHistory,omitempty"`
	// LastSharedMethod undocumented
	LastSharedMethod *Entity `json:"lastSharedMethod,omitempty"`
	// Resource undocumented
	Resource *Entity `json:"resource,omitempty"`
}

// SharedPCAccountManagerPolicy undocumented
type SharedPCAccountManagerPolicy struct {
	// Object is the base model of SharedPCAccountManagerPolicy
	Object
	// AccountDeletionPolicy undocumented
	AccountDeletionPolicy *SharedPCAccountDeletionPolicyType `json:"accountDeletionPolicy,omitempty"`
	// CacheAccountsAboveDiskFreePercentage undocumented
	CacheAccountsAboveDiskFreePercentage *int `json:"cacheAccountsAboveDiskFreePercentage,omitempty"`
	// InactiveThresholdDays undocumented
	InactiveThresholdDays *int `json:"inactiveThresholdDays,omitempty"`
	// RemoveAccountsBelowDiskFreePercentage undocumented
	RemoveAccountsBelowDiskFreePercentage *int `json:"removeAccountsBelowDiskFreePercentage,omitempty"`
}

// SharedPCConfiguration undocumented
type SharedPCConfiguration struct {
	// DeviceConfiguration is the base model of SharedPCConfiguration
	DeviceConfiguration
	// AccountManagerPolicy undocumented
	AccountManagerPolicy *SharedPCAccountManagerPolicy `json:"accountManagerPolicy,omitempty"`
	// AllowedAccounts undocumented
	AllowedAccounts *SharedPCAllowedAccountType `json:"allowedAccounts,omitempty"`
	// AllowLocalStorage undocumented
	AllowLocalStorage *bool `json:"allowLocalStorage,omitempty"`
	// DisableAccountManager undocumented
	DisableAccountManager *bool `json:"disableAccountManager,omitempty"`
	// DisableEduPolicies undocumented
	DisableEduPolicies *bool `json:"disableEduPolicies,omitempty"`
	// DisablePowerPolicies undocumented
	DisablePowerPolicies *bool `json:"disablePowerPolicies,omitempty"`
	// DisableSignInOnResume undocumented
	DisableSignInOnResume *bool `json:"disableSignInOnResume,omitempty"`
	// Enabled undocumented
	Enabled *bool `json:"enabled,omitempty"`
	// IdleTimeBeforeSleepInSeconds undocumented
	IdleTimeBeforeSleepInSeconds *int `json:"idleTimeBeforeSleepInSeconds,omitempty"`
	// KioskAppDisplayName undocumented
	KioskAppDisplayName *string `json:"kioskAppDisplayName,omitempty"`
	// KioskAppUserModelID undocumented
	KioskAppUserModelID *string `json:"kioskAppUserModelId,omitempty"`
	// MaintenanceStartTime undocumented
	MaintenanceStartTime *TimeOfDay `json:"maintenanceStartTime,omitempty"`
}

// SharedWithChannelTeamInfo undocumented
type SharedWithChannelTeamInfo struct {
	// TeamInfo is the base model of SharedWithChannelTeamInfo
	TeamInfo
	// IsHostTeam undocumented
	IsHostTeam *bool `json:"isHostTeam,omitempty"`
	// AllowedMembers undocumented
	AllowedMembers []ConversationMember `json:"allowedMembers,omitempty"`
}
