// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// LocalizedNotificationMessage undocumented
type LocalizedNotificationMessage struct {
	// Entity is the base model of LocalizedNotificationMessage
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// IsDefault undocumented
	IsDefault *bool `json:"isDefault,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// Locale undocumented
	Locale *string `json:"locale,omitempty"`
	// MessageTemplate undocumented
	MessageTemplate *string `json:"messageTemplate,omitempty"`
	// Subject undocumented
	Subject *string `json:"subject,omitempty"`
}

func NewLocalizedNotificationMessage() (*LocalizedNotificationMessage, error) {
	newLocalizedNotificationMessage := &LocalizedNotificationMessage{
		ODataType: "#microsoft.graph.LocalizedNotificationMessage",
	}
	return newLocalizedNotificationMessage, nil
}
