// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// BasicAuthentication undocumented
type BasicAuthentication struct {
	// APIAuthenticationConfigurationBase is the base model of BasicAuthentication
	APIAuthenticationConfigurationBase
	// Password undocumented
	Password *string `json:"password,omitempty"`
	// Username undocumented
	Username *string `json:"username,omitempty"`
}
