// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// ConvertIDResult undocumented
type ConvertIDResult struct {
	// Object is the base model of ConvertIDResult
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// ErrorDetails undocumented
	ErrorDetails *GenericError `json:"errorDetails,omitempty"`
	// SourceID undocumented
	SourceID *string `json:"sourceId,omitempty"`
	// TargetID undocumented
	TargetID *string `json:"targetId,omitempty"`
}

func NewConvertIDResult() (*ConvertIDResult, error) {
	newConvertIDResult := &ConvertIDResult{
		ODataType: "#microsoft.graph.ConvertIdResult",
	}
	return newConvertIDResult, nil
}
