// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// MeetingAttendanceReport undocumented
type MeetingAttendanceReport struct {
	// Entity is the base model of MeetingAttendanceReport
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// MeetingEndDateTime undocumented
	MeetingEndDateTime *time.Time `json:"meetingEndDateTime,omitempty"`
	// MeetingStartDateTime undocumented
	MeetingStartDateTime *time.Time `json:"meetingStartDateTime,omitempty"`
	// TotalParticipantCount undocumented
	TotalParticipantCount *int `json:"totalParticipantCount,omitempty"`
	// AttendanceRecords undocumented
	AttendanceRecords []AttendanceRecord `json:"attendanceRecords,omitempty"`
}

func NewMeetingAttendanceReport() (*MeetingAttendanceReport, error) {
	newMeetingAttendanceReport := &MeetingAttendanceReport{
		ODataType: "#microsoft.graph.MeetingAttendanceReport",
	}
	return newMeetingAttendanceReport, nil
}

// MeetingInfo undocumented
type MeetingInfo struct {
	// Object is the base model of MeetingInfo
	Object

	ODataType string `json:"@odata.type,omitempty"`
}

func NewMeetingInfo() (*MeetingInfo, error) {
	newMeetingInfo := &MeetingInfo{
		ODataType: "#microsoft.graph.MeetingInfo",
	}
	return newMeetingInfo, nil
}

// MeetingParticipantInfo undocumented
type MeetingParticipantInfo struct {
	// Object is the base model of MeetingParticipantInfo
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// Identity undocumented
	Identity *IdentitySet `json:"identity,omitempty"`
	// Role undocumented
	Role *OnlineMeetingRole `json:"role,omitempty"`
	// Upn undocumented
	Upn *string `json:"upn,omitempty"`
}

func NewMeetingParticipantInfo() (*MeetingParticipantInfo, error) {
	newMeetingParticipantInfo := &MeetingParticipantInfo{
		ODataType: "#microsoft.graph.MeetingParticipantInfo",
	}
	return newMeetingParticipantInfo, nil
}

// MeetingParticipants undocumented
type MeetingParticipants struct {
	// Object is the base model of MeetingParticipants
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// Attendees undocumented
	Attendees []MeetingParticipantInfo `json:"attendees,omitempty"`
	// Organizer undocumented
	Organizer *MeetingParticipantInfo `json:"organizer,omitempty"`
}

func NewMeetingParticipants() (*MeetingParticipants, error) {
	newMeetingParticipants := &MeetingParticipants{
		ODataType: "#microsoft.graph.MeetingParticipants",
	}
	return newMeetingParticipants, nil
}

// MeetingPolicyUpdatedEventMessageDetail undocumented
type MeetingPolicyUpdatedEventMessageDetail struct {
	// EventMessageDetail is the base model of MeetingPolicyUpdatedEventMessageDetail
	EventMessageDetail

	ODataType string `json:"@odata.type,omitempty"`
	// Initiator undocumented
	Initiator *IdentitySet `json:"initiator,omitempty"`
	// MeetingChatEnabled undocumented
	MeetingChatEnabled *bool `json:"meetingChatEnabled,omitempty"`
	// MeetingChatID undocumented
	MeetingChatID *string `json:"meetingChatId,omitempty"`
}

func NewMeetingPolicyUpdatedEventMessageDetail() (*MeetingPolicyUpdatedEventMessageDetail, error) {
	newMeetingPolicyUpdatedEventMessageDetail := &MeetingPolicyUpdatedEventMessageDetail{
		ODataType: "#microsoft.graph.MeetingPolicyUpdatedEventMessageDetail",
	}
	return newMeetingPolicyUpdatedEventMessageDetail, nil
}

// MeetingTimeSuggestion undocumented
type MeetingTimeSuggestion struct {
	// Object is the base model of MeetingTimeSuggestion
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// AttendeeAvailability undocumented
	AttendeeAvailability []AttendeeAvailability `json:"attendeeAvailability,omitempty"`
	// Confidence undocumented
	Confidence *float64 `json:"confidence,omitempty"`
	// Locations undocumented
	Locations []Location `json:"locations,omitempty"`
	// MeetingTimeSlot undocumented
	MeetingTimeSlot *TimeSlot `json:"meetingTimeSlot,omitempty"`
	// Order undocumented
	Order *int `json:"order,omitempty"`
	// OrganizerAvailability undocumented
	OrganizerAvailability *FreeBusyStatus `json:"organizerAvailability,omitempty"`
	// SuggestionReason undocumented
	SuggestionReason *string `json:"suggestionReason,omitempty"`
}

func NewMeetingTimeSuggestion() (*MeetingTimeSuggestion, error) {
	newMeetingTimeSuggestion := &MeetingTimeSuggestion{
		ODataType: "#microsoft.graph.MeetingTimeSuggestion",
	}
	return newMeetingTimeSuggestion, nil
}

// MeetingTimeSuggestionsResult undocumented
type MeetingTimeSuggestionsResult struct {
	// Object is the base model of MeetingTimeSuggestionsResult
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// EmptySuggestionsReason undocumented
	EmptySuggestionsReason *string `json:"emptySuggestionsReason,omitempty"`
	// MeetingTimeSuggestions undocumented
	MeetingTimeSuggestions []MeetingTimeSuggestion `json:"meetingTimeSuggestions,omitempty"`
}

func NewMeetingTimeSuggestionsResult() (*MeetingTimeSuggestionsResult, error) {
	newMeetingTimeSuggestionsResult := &MeetingTimeSuggestionsResult{
		ODataType: "#microsoft.graph.MeetingTimeSuggestionsResult",
	}
	return newMeetingTimeSuggestionsResult, nil
}
