// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// ClientCertificateAuthenticationRequestBuilder is request builder for ClientCertificateAuthentication
type ClientCertificateAuthenticationRequestBuilder struct{ BaseRequestBuilder }

// Request returns ClientCertificateAuthenticationRequest
func (b *ClientCertificateAuthenticationRequestBuilder) Request() *ClientCertificateAuthenticationRequest {
	return &ClientCertificateAuthenticationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ClientCertificateAuthenticationRequest is request for ClientCertificateAuthentication
type ClientCertificateAuthenticationRequest struct{ BaseRequest }

// Get performs GET request for ClientCertificateAuthentication
func (r *ClientCertificateAuthenticationRequest) Get(ctx context.Context) (resObj *ClientCertificateAuthentication, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for ClientCertificateAuthentication
func (r *ClientCertificateAuthenticationRequest) Update(ctx context.Context, reqObj *ClientCertificateAuthentication) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for ClientCertificateAuthentication
func (r *ClientCertificateAuthenticationRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
