// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// CallRequestBuilder is request builder for Call
type CallRequestBuilder struct{ BaseRequestBuilder }

// Request returns CallRequest
func (b *CallRequestBuilder) Request() *CallRequest {
	return &CallRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// CallRequest is request for Call
type CallRequest struct{ BaseRequest }

// Get performs GET request for Call
func (r *CallRequest) Get(ctx context.Context) (resObj *Call, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Call
func (r *CallRequest) Update(ctx context.Context, reqObj *Call) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Call
func (r *CallRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// CallRecordsCallRecordRequestBuilder is request builder for CallRecordsCallRecord
type CallRecordsCallRecordRequestBuilder struct{ BaseRequestBuilder }

// Request returns CallRecordsCallRecordRequest
func (b *CallRecordsCallRecordRequestBuilder) Request() *CallRecordsCallRecordRequest {
	return &CallRecordsCallRecordRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// CallRecordsCallRecordRequest is request for CallRecordsCallRecord
type CallRecordsCallRecordRequest struct{ BaseRequest }

// Get performs GET request for CallRecordsCallRecord
func (r *CallRecordsCallRecordRequest) Get(ctx context.Context) (resObj *CallRecordsCallRecord, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for CallRecordsCallRecord
func (r *CallRecordsCallRecordRequest) Update(ctx context.Context, reqObj *CallRecordsCallRecord) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for CallRecordsCallRecord
func (r *CallRecordsCallRecordRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

type CallCollectionLogTeleconferenceDeviceQualityRequestBuilder struct{ BaseRequestBuilder }

// LogTeleconferenceDeviceQuality action undocumented
func (b *CloudCommunicationsCallsCollectionRequestBuilder) LogTeleconferenceDeviceQuality(reqObj *CallCollectionLogTeleconferenceDeviceQualityRequestParameter) *CallCollectionLogTeleconferenceDeviceQualityRequestBuilder {
	bb := &CallCollectionLogTeleconferenceDeviceQualityRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.BaseRequestBuilder.baseURL += "/LogTeleconferenceDeviceQuality"
	bb.BaseRequestBuilder.requestObject = reqObj
	return bb
}

type CallCollectionLogTeleconferenceDeviceQualityRequest struct{ BaseRequest }

func (b *CallCollectionLogTeleconferenceDeviceQualityRequestBuilder) Request() *CallCollectionLogTeleconferenceDeviceQualityRequest {
	return &CallCollectionLogTeleconferenceDeviceQualityRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client, requestObject: b.requestObject},
	}
}

func (r *CallCollectionLogTeleconferenceDeviceQualityRequest) Post(ctx context.Context) error {
	return r.JSONRequest(ctx, "POST", "", r.requestObject, nil)
}

// CallRecordsSegmentRequestBuilder is request builder for CallRecordsSegment
type CallRecordsSegmentRequestBuilder struct{ BaseRequestBuilder }

// Request returns CallRecordsSegmentRequest
func (b *CallRecordsSegmentRequestBuilder) Request() *CallRecordsSegmentRequest {
	return &CallRecordsSegmentRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// CallRecordsSegmentRequest is request for CallRecordsSegment
type CallRecordsSegmentRequest struct{ BaseRequest }

// Get performs GET request for CallRecordsSegment
func (r *CallRecordsSegmentRequest) Get(ctx context.Context) (resObj *CallRecordsSegment, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for CallRecordsSegment
func (r *CallRecordsSegmentRequest) Update(ctx context.Context, reqObj *CallRecordsSegment) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for CallRecordsSegment
func (r *CallRecordsSegmentRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// CallRecordsSessionRequestBuilder is request builder for CallRecordsSession
type CallRecordsSessionRequestBuilder struct{ BaseRequestBuilder }

// Request returns CallRecordsSessionRequest
func (b *CallRecordsSessionRequestBuilder) Request() *CallRecordsSessionRequest {
	return &CallRecordsSessionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// CallRecordsSessionRequest is request for CallRecordsSession
type CallRecordsSessionRequest struct{ BaseRequest }

// Get performs GET request for CallRecordsSession
func (r *CallRecordsSessionRequest) Get(ctx context.Context) (resObj *CallRecordsSession, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for CallRecordsSession
func (r *CallRecordsSessionRequest) Update(ctx context.Context, reqObj *CallRecordsSession) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for CallRecordsSession
func (r *CallRecordsSessionRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
