// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// X509CertificateAuthenticationMethodConfigurationRequestBuilder is request builder for X509CertificateAuthenticationMethodConfiguration
type X509CertificateAuthenticationMethodConfigurationRequestBuilder struct{ BaseRequestBuilder }

// Request returns X509CertificateAuthenticationMethodConfigurationRequest
func (b *X509CertificateAuthenticationMethodConfigurationRequestBuilder) Request() *X509CertificateAuthenticationMethodConfigurationRequest {
	return &X509CertificateAuthenticationMethodConfigurationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// X509CertificateAuthenticationMethodConfigurationRequest is request for X509CertificateAuthenticationMethodConfiguration
type X509CertificateAuthenticationMethodConfigurationRequest struct{ BaseRequest }

// Get performs GET request for X509CertificateAuthenticationMethodConfiguration
func (r *X509CertificateAuthenticationMethodConfigurationRequest) Get(ctx context.Context) (resObj *X509CertificateAuthenticationMethodConfiguration, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for X509CertificateAuthenticationMethodConfiguration
func (r *X509CertificateAuthenticationMethodConfigurationRequest) Update(ctx context.Context, reqObj *X509CertificateAuthenticationMethodConfiguration) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for X509CertificateAuthenticationMethodConfiguration
func (r *X509CertificateAuthenticationMethodConfigurationRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
