// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// ReferenceAttachmentRequestBuilder is request builder for ReferenceAttachment
type ReferenceAttachmentRequestBuilder struct{ BaseRequestBuilder }

// Request returns ReferenceAttachmentRequest
func (b *ReferenceAttachmentRequestBuilder) Request() *ReferenceAttachmentRequest {
	return &ReferenceAttachmentRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ReferenceAttachmentRequest is request for ReferenceAttachment
type ReferenceAttachmentRequest struct{ BaseRequest }

// Get performs GET request for ReferenceAttachment
func (r *ReferenceAttachmentRequest) Get(ctx context.Context) (resObj *ReferenceAttachment, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for ReferenceAttachment
func (r *ReferenceAttachmentRequest) Update(ctx context.Context, reqObj *ReferenceAttachment) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for ReferenceAttachment
func (r *ReferenceAttachmentRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
