// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// PhotoRequestBuilder is request builder for Photo
type PhotoRequestBuilder struct{ BaseRequestBuilder }

// Request returns PhotoRequest
func (b *PhotoRequestBuilder) Request() *PhotoRequest {
	return &PhotoRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// PhotoRequest is request for Photo
type PhotoRequest struct{ BaseRequest }

// Get performs GET request for Photo
func (r *PhotoRequest) Get(ctx context.Context) (resObj *Photo, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Photo
func (r *PhotoRequest) Update(ctx context.Context, reqObj *Photo) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Photo
func (r *PhotoRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
