// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/BenHagueNZ/msgraph.go/jsonx"
)

// Connections returns request builder for ExternalConnection collection
func (b *ExternalRequestBuilder) Connections() *ExternalConnectionsCollectionRequestBuilder {
	bb := &ExternalConnectionsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/connections"
	return bb
}

// ExternalConnectionsCollectionRequestBuilder is request builder for ExternalConnection collection rcn
type ExternalConnectionsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalConnection collection
func (b *ExternalConnectionsCollectionRequestBuilder) Request() *ExternalConnectionsCollectionRequest {
	return &ExternalConnectionsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalConnection item
func (b *ExternalConnectionsCollectionRequestBuilder) ID(id string) *ExternalConnectionRequestBuilder {
	bb := &ExternalConnectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectionsCollectionRequest is request for ExternalConnection collection
type ExternalConnectionsCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalConnection collection
func (r *ExternalConnectionsCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalConnection, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalConnection
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalConnection
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalConnection collection, max N pages
func (r *ExternalConnectionsCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalConnection, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalConnection collection
func (r *ExternalConnectionsCollectionRequest) Get(ctx context.Context) ([]ExternalConnection, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalConnection collection
func (r *ExternalConnectionsCollectionRequest) Add(ctx context.Context, reqObj *ExternalConnection) (resObj *ExternalConnection, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// Groups returns request builder for ExternalGroup collection
func (b *ExternalConnectionRequestBuilder) Groups() *ExternalConnectionGroupsCollectionRequestBuilder {
	bb := &ExternalConnectionGroupsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/groups"
	return bb
}

// ExternalConnectionGroupsCollectionRequestBuilder is request builder for ExternalGroup collection rcn
type ExternalConnectionGroupsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalGroup collection
func (b *ExternalConnectionGroupsCollectionRequestBuilder) Request() *ExternalConnectionGroupsCollectionRequest {
	return &ExternalConnectionGroupsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalGroup item
func (b *ExternalConnectionGroupsCollectionRequestBuilder) ID(id string) *ExternalGroupRequestBuilder {
	bb := &ExternalGroupRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectionGroupsCollectionRequest is request for ExternalGroup collection
type ExternalConnectionGroupsCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalGroup collection
func (r *ExternalConnectionGroupsCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalGroup, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalGroup
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalGroup
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalGroup collection, max N pages
func (r *ExternalConnectionGroupsCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalGroup, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalGroup collection
func (r *ExternalConnectionGroupsCollectionRequest) Get(ctx context.Context) ([]ExternalGroup, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalGroup collection
func (r *ExternalConnectionGroupsCollectionRequest) Add(ctx context.Context, reqObj *ExternalGroup) (resObj *ExternalGroup, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// Items returns request builder for ExternalItem collection
func (b *ExternalConnectionRequestBuilder) Items() *ExternalConnectionItemsCollectionRequestBuilder {
	bb := &ExternalConnectionItemsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/items"
	return bb
}

// ExternalConnectionItemsCollectionRequestBuilder is request builder for ExternalItem collection rcn
type ExternalConnectionItemsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalItem collection
func (b *ExternalConnectionItemsCollectionRequestBuilder) Request() *ExternalConnectionItemsCollectionRequest {
	return &ExternalConnectionItemsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalItem item
func (b *ExternalConnectionItemsCollectionRequestBuilder) ID(id string) *ExternalItemRequestBuilder {
	bb := &ExternalItemRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectionItemsCollectionRequest is request for ExternalItem collection
type ExternalConnectionItemsCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalItem collection
func (r *ExternalConnectionItemsCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalItem, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalItem
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalItem
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalItem collection, max N pages
func (r *ExternalConnectionItemsCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalItem, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalItem collection
func (r *ExternalConnectionItemsCollectionRequest) Get(ctx context.Context) ([]ExternalItem, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalItem collection
func (r *ExternalConnectionItemsCollectionRequest) Add(ctx context.Context, reqObj *ExternalItem) (resObj *ExternalItem, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// Operations returns request builder for ConnectionOperation collection
func (b *ExternalConnectionRequestBuilder) Operations() *ExternalConnectionOperationsCollectionRequestBuilder {
	bb := &ExternalConnectionOperationsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/operations"
	return bb
}

// ExternalConnectionOperationsCollectionRequestBuilder is request builder for ConnectionOperation collection rcn
type ExternalConnectionOperationsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ConnectionOperation collection
func (b *ExternalConnectionOperationsCollectionRequestBuilder) Request() *ExternalConnectionOperationsCollectionRequest {
	return &ExternalConnectionOperationsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ConnectionOperation item
func (b *ExternalConnectionOperationsCollectionRequestBuilder) ID(id string) *ConnectionOperationRequestBuilder {
	bb := &ConnectionOperationRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectionOperationsCollectionRequest is request for ConnectionOperation collection
type ExternalConnectionOperationsCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ConnectionOperation collection
func (r *ExternalConnectionOperationsCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ConnectionOperation, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ConnectionOperation
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ConnectionOperation
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ConnectionOperation collection, max N pages
func (r *ExternalConnectionOperationsCollectionRequest) GetN(ctx context.Context, n int) ([]ConnectionOperation, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ConnectionOperation collection
func (r *ExternalConnectionOperationsCollectionRequest) Get(ctx context.Context) ([]ConnectionOperation, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ConnectionOperation collection
func (r *ExternalConnectionOperationsCollectionRequest) Add(ctx context.Context, reqObj *ConnectionOperation) (resObj *ConnectionOperation, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// Schema is navigation property rn
func (b *ExternalConnectionRequestBuilder) Schema() *SchemaRequestBuilder {
	bb := &SchemaRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/schema"
	return bb
}

// Entity is navigation property rn
func (b *ExternalRequestBuilder) Entity() *EntityRequestBuilder {
	bb := &EntityRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/Entity"
	return bb
}

// Entity is navigation property rn
func (b *ExternalConnectionRequestBuilder) Entity() *EntityRequestBuilder {
	bb := &EntityRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/Entity"
	return bb
}

// Entity is navigation property rn
func (b *ExternalDomainNameRequestBuilder) Entity() *EntityRequestBuilder {
	bb := &EntityRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/Entity"
	return bb
}

// Entity is navigation property rn
func (b *ExternalGroupRequestBuilder) Entity() *EntityRequestBuilder {
	bb := &EntityRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/Entity"
	return bb
}

// Entity is navigation property rn
func (b *ExternalItemRequestBuilder) Entity() *EntityRequestBuilder {
	bb := &EntityRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/Entity"
	return bb
}

// ExternalMeetingRegistrant returns request builder for ExternalMeetingRegistrant collection
func (b *MeetingRegistrationBaseRegistrantsCollectionRequestBuilder) ExternalMeetingRegistrant() *MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequestBuilder {
	bb := &MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/"
	return bb
}

// MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequestBuilder is request builder for ExternalMeetingRegistrant collection rcn
type MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalMeetingRegistrant collection
func (b *MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequestBuilder) Request() *MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequest {
	return &MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalMeetingRegistrant item
func (b *MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequestBuilder) ID(id string) *ExternalMeetingRegistrantRequestBuilder {
	bb := &ExternalMeetingRegistrantRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequest is request for ExternalMeetingRegistrant collection
type MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalMeetingRegistrant collection
func (r *MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalMeetingRegistrant, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalMeetingRegistrant
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalMeetingRegistrant
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalMeetingRegistrant collection, max N pages
func (r *MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalMeetingRegistrant, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalMeetingRegistrant collection
func (r *MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequest) Get(ctx context.Context) ([]ExternalMeetingRegistrant, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalMeetingRegistrant collection
func (r *MeetingRegistrationBaseRegistrantsCollectionExternalMeetingRegistrantCollectionRequest) Add(ctx context.Context, reqObj *ExternalMeetingRegistrant) (resObj *ExternalMeetingRegistrant, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// ExternalConnectorsExternalItemExternalConnectorsAddActivitiesRequestParameter undocumented
type ExternalConnectorsExternalItemExternalConnectorsAddActivitiesRequestParameter struct {
	// Activities undocumented
	Activities []ExternalConnectorsExternalActivity `json:"activities,omitempty"`
}

// Connections returns request builder for ExternalConnectorsExternalConnection collection
func (b *ExternalConnectorsExternalRequestBuilder) Connections() *ExternalConnectorsExternalConnectionsCollectionRequestBuilder {
	bb := &ExternalConnectorsExternalConnectionsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/connections"
	return bb
}

// ExternalConnectorsExternalConnectionsCollectionRequestBuilder is request builder for ExternalConnectorsExternalConnection collection rcn
type ExternalConnectorsExternalConnectionsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalConnectorsExternalConnection collection
func (b *ExternalConnectorsExternalConnectionsCollectionRequestBuilder) Request() *ExternalConnectorsExternalConnectionsCollectionRequest {
	return &ExternalConnectorsExternalConnectionsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalConnectorsExternalConnection item
func (b *ExternalConnectorsExternalConnectionsCollectionRequestBuilder) ID(id string) *ExternalConnectorsExternalConnectionRequestBuilder {
	bb := &ExternalConnectorsExternalConnectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectorsExternalConnectionsCollectionRequest is request for ExternalConnectorsExternalConnection collection
type ExternalConnectorsExternalConnectionsCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalConnectorsExternalConnection collection
func (r *ExternalConnectorsExternalConnectionsCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalConnectorsExternalConnection, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalConnectorsExternalConnection
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalConnectorsExternalConnection
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalConnectorsExternalConnection collection, max N pages
func (r *ExternalConnectorsExternalConnectionsCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalConnectorsExternalConnection, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalConnectorsExternalConnection collection
func (r *ExternalConnectorsExternalConnectionsCollectionRequest) Get(ctx context.Context) ([]ExternalConnectorsExternalConnection, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalConnectorsExternalConnection collection
func (r *ExternalConnectorsExternalConnectionsCollectionRequest) Add(ctx context.Context, reqObj *ExternalConnectorsExternalConnection) (resObj *ExternalConnectorsExternalConnection, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// IndustryData is navigation property rn
func (b *ExternalConnectorsExternalRequestBuilder) IndustryData() *IndustryDataIndustryDataRootRequestBuilder {
	bb := &IndustryDataIndustryDataRootRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/industryData"
	return bb
}

// PerformedBy is navigation property rn
func (b *ExternalConnectorsExternalActivityRequestBuilder) PerformedBy() *ExternalConnectorsIdentityRequestBuilder {
	bb := &ExternalConnectorsIdentityRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/performedBy"
	return bb
}

// Groups returns request builder for ExternalConnectorsExternalGroup collection
func (b *ExternalConnectorsExternalConnectionRequestBuilder) Groups() *ExternalConnectorsExternalConnectionGroupsCollectionRequestBuilder {
	bb := &ExternalConnectorsExternalConnectionGroupsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/groups"
	return bb
}

// ExternalConnectorsExternalConnectionGroupsCollectionRequestBuilder is request builder for ExternalConnectorsExternalGroup collection rcn
type ExternalConnectorsExternalConnectionGroupsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalConnectorsExternalGroup collection
func (b *ExternalConnectorsExternalConnectionGroupsCollectionRequestBuilder) Request() *ExternalConnectorsExternalConnectionGroupsCollectionRequest {
	return &ExternalConnectorsExternalConnectionGroupsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalConnectorsExternalGroup item
func (b *ExternalConnectorsExternalConnectionGroupsCollectionRequestBuilder) ID(id string) *ExternalConnectorsExternalGroupRequestBuilder {
	bb := &ExternalConnectorsExternalGroupRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectorsExternalConnectionGroupsCollectionRequest is request for ExternalConnectorsExternalGroup collection
type ExternalConnectorsExternalConnectionGroupsCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalConnectorsExternalGroup collection
func (r *ExternalConnectorsExternalConnectionGroupsCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalConnectorsExternalGroup, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalConnectorsExternalGroup
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalConnectorsExternalGroup
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalConnectorsExternalGroup collection, max N pages
func (r *ExternalConnectorsExternalConnectionGroupsCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalConnectorsExternalGroup, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalConnectorsExternalGroup collection
func (r *ExternalConnectorsExternalConnectionGroupsCollectionRequest) Get(ctx context.Context) ([]ExternalConnectorsExternalGroup, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalConnectorsExternalGroup collection
func (r *ExternalConnectorsExternalConnectionGroupsCollectionRequest) Add(ctx context.Context, reqObj *ExternalConnectorsExternalGroup) (resObj *ExternalConnectorsExternalGroup, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// Items returns request builder for ExternalConnectorsExternalItem collection
func (b *ExternalConnectorsExternalConnectionRequestBuilder) Items() *ExternalConnectorsExternalConnectionItemsCollectionRequestBuilder {
	bb := &ExternalConnectorsExternalConnectionItemsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/items"
	return bb
}

// ExternalConnectorsExternalConnectionItemsCollectionRequestBuilder is request builder for ExternalConnectorsExternalItem collection rcn
type ExternalConnectorsExternalConnectionItemsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalConnectorsExternalItem collection
func (b *ExternalConnectorsExternalConnectionItemsCollectionRequestBuilder) Request() *ExternalConnectorsExternalConnectionItemsCollectionRequest {
	return &ExternalConnectorsExternalConnectionItemsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalConnectorsExternalItem item
func (b *ExternalConnectorsExternalConnectionItemsCollectionRequestBuilder) ID(id string) *ExternalConnectorsExternalItemRequestBuilder {
	bb := &ExternalConnectorsExternalItemRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectorsExternalConnectionItemsCollectionRequest is request for ExternalConnectorsExternalItem collection
type ExternalConnectorsExternalConnectionItemsCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalConnectorsExternalItem collection
func (r *ExternalConnectorsExternalConnectionItemsCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalConnectorsExternalItem, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalConnectorsExternalItem
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalConnectorsExternalItem
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalConnectorsExternalItem collection, max N pages
func (r *ExternalConnectorsExternalConnectionItemsCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalConnectorsExternalItem, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalConnectorsExternalItem collection
func (r *ExternalConnectorsExternalConnectionItemsCollectionRequest) Get(ctx context.Context) ([]ExternalConnectorsExternalItem, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalConnectorsExternalItem collection
func (r *ExternalConnectorsExternalConnectionItemsCollectionRequest) Add(ctx context.Context, reqObj *ExternalConnectorsExternalItem) (resObj *ExternalConnectorsExternalItem, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// Operations returns request builder for ExternalConnectorsConnectionOperation collection
func (b *ExternalConnectorsExternalConnectionRequestBuilder) Operations() *ExternalConnectorsExternalConnectionOperationsCollectionRequestBuilder {
	bb := &ExternalConnectorsExternalConnectionOperationsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/operations"
	return bb
}

// ExternalConnectorsExternalConnectionOperationsCollectionRequestBuilder is request builder for ExternalConnectorsConnectionOperation collection rcn
type ExternalConnectorsExternalConnectionOperationsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalConnectorsConnectionOperation collection
func (b *ExternalConnectorsExternalConnectionOperationsCollectionRequestBuilder) Request() *ExternalConnectorsExternalConnectionOperationsCollectionRequest {
	return &ExternalConnectorsExternalConnectionOperationsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalConnectorsConnectionOperation item
func (b *ExternalConnectorsExternalConnectionOperationsCollectionRequestBuilder) ID(id string) *ExternalConnectorsConnectionOperationRequestBuilder {
	bb := &ExternalConnectorsConnectionOperationRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectorsExternalConnectionOperationsCollectionRequest is request for ExternalConnectorsConnectionOperation collection
type ExternalConnectorsExternalConnectionOperationsCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalConnectorsConnectionOperation collection
func (r *ExternalConnectorsExternalConnectionOperationsCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalConnectorsConnectionOperation, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalConnectorsConnectionOperation
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalConnectorsConnectionOperation
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalConnectorsConnectionOperation collection, max N pages
func (r *ExternalConnectorsExternalConnectionOperationsCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalConnectorsConnectionOperation, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalConnectorsConnectionOperation collection
func (r *ExternalConnectorsExternalConnectionOperationsCollectionRequest) Get(ctx context.Context) ([]ExternalConnectorsConnectionOperation, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalConnectorsConnectionOperation collection
func (r *ExternalConnectorsExternalConnectionOperationsCollectionRequest) Add(ctx context.Context, reqObj *ExternalConnectorsConnectionOperation) (resObj *ExternalConnectorsConnectionOperation, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// Quota is navigation property rn
func (b *ExternalConnectorsExternalConnectionRequestBuilder) Quota() *ExternalConnectorsConnectionQuotaRequestBuilder {
	bb := &ExternalConnectorsConnectionQuotaRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/quota"
	return bb
}

// Schema is navigation property rn
func (b *ExternalConnectorsExternalConnectionRequestBuilder) Schema() *ExternalConnectorsSchemaRequestBuilder {
	bb := &ExternalConnectorsSchemaRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/schema"
	return bb
}

// Members returns request builder for ExternalConnectorsIdentity collection
func (b *ExternalConnectorsExternalGroupRequestBuilder) Members() *ExternalConnectorsExternalGroupMembersCollectionRequestBuilder {
	bb := &ExternalConnectorsExternalGroupMembersCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/members"
	return bb
}

// ExternalConnectorsExternalGroupMembersCollectionRequestBuilder is request builder for ExternalConnectorsIdentity collection rcn
type ExternalConnectorsExternalGroupMembersCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalConnectorsIdentity collection
func (b *ExternalConnectorsExternalGroupMembersCollectionRequestBuilder) Request() *ExternalConnectorsExternalGroupMembersCollectionRequest {
	return &ExternalConnectorsExternalGroupMembersCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalConnectorsIdentity item
func (b *ExternalConnectorsExternalGroupMembersCollectionRequestBuilder) ID(id string) *ExternalConnectorsIdentityRequestBuilder {
	bb := &ExternalConnectorsIdentityRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectorsExternalGroupMembersCollectionRequest is request for ExternalConnectorsIdentity collection
type ExternalConnectorsExternalGroupMembersCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalConnectorsIdentity collection
func (r *ExternalConnectorsExternalGroupMembersCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalConnectorsIdentity, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalConnectorsIdentity
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalConnectorsIdentity
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalConnectorsIdentity collection, max N pages
func (r *ExternalConnectorsExternalGroupMembersCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalConnectorsIdentity, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalConnectorsIdentity collection
func (r *ExternalConnectorsExternalGroupMembersCollectionRequest) Get(ctx context.Context) ([]ExternalConnectorsIdentity, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalConnectorsIdentity collection
func (r *ExternalConnectorsExternalGroupMembersCollectionRequest) Add(ctx context.Context, reqObj *ExternalConnectorsIdentity) (resObj *ExternalConnectorsIdentity, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// Activities returns request builder for ExternalConnectorsExternalActivity collection
func (b *ExternalConnectorsExternalItemRequestBuilder) Activities() *ExternalConnectorsExternalItemActivitiesCollectionRequestBuilder {
	bb := &ExternalConnectorsExternalItemActivitiesCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/activities"
	return bb
}

// ExternalConnectorsExternalItemActivitiesCollectionRequestBuilder is request builder for ExternalConnectorsExternalActivity collection rcn
type ExternalConnectorsExternalItemActivitiesCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalConnectorsExternalActivity collection
func (b *ExternalConnectorsExternalItemActivitiesCollectionRequestBuilder) Request() *ExternalConnectorsExternalItemActivitiesCollectionRequest {
	return &ExternalConnectorsExternalItemActivitiesCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalConnectorsExternalActivity item
func (b *ExternalConnectorsExternalItemActivitiesCollectionRequestBuilder) ID(id string) *ExternalConnectorsExternalActivityRequestBuilder {
	bb := &ExternalConnectorsExternalActivityRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectorsExternalItemActivitiesCollectionRequest is request for ExternalConnectorsExternalActivity collection
type ExternalConnectorsExternalItemActivitiesCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalConnectorsExternalActivity collection
func (r *ExternalConnectorsExternalItemActivitiesCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalConnectorsExternalActivity, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalConnectorsExternalActivity
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalConnectorsExternalActivity
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalConnectorsExternalActivity collection, max N pages
func (r *ExternalConnectorsExternalItemActivitiesCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalConnectorsExternalActivity, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalConnectorsExternalActivity collection
func (r *ExternalConnectorsExternalItemActivitiesCollectionRequest) Get(ctx context.Context) ([]ExternalConnectorsExternalActivity, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalConnectorsExternalActivity collection
func (r *ExternalConnectorsExternalItemActivitiesCollectionRequest) Add(ctx context.Context, reqObj *ExternalConnectorsExternalActivity) (resObj *ExternalConnectorsExternalActivity, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// ExternalConnectorsExternalActivityResult returns request builder for ExternalConnectorsExternalActivityResult collection
func (b *ExternalConnectorsExternalActivityRequestBuilder) ExternalConnectorsExternalActivityResult() *ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequestBuilder {
	bb := &ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/"
	return bb
}

// ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequestBuilder is request builder for ExternalConnectorsExternalActivityResult collection rcn
type ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ExternalConnectorsExternalActivityResult collection
func (b *ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequestBuilder) Request() *ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequest {
	return &ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ExternalConnectorsExternalActivityResult item
func (b *ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequestBuilder) ID(id string) *ExternalConnectorsExternalActivityResultRequestBuilder {
	bb := &ExternalConnectorsExternalActivityResultRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequest is request for ExternalConnectorsExternalActivityResult collection
type ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ExternalConnectorsExternalActivityResult collection
func (r *ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ExternalConnectorsExternalActivityResult, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ExternalConnectorsExternalActivityResult
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ExternalConnectorsExternalActivityResult
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ExternalConnectorsExternalActivityResult collection, max N pages
func (r *ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequest) GetN(ctx context.Context, n int) ([]ExternalConnectorsExternalActivityResult, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ExternalConnectorsExternalActivityResult collection
func (r *ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequest) Get(ctx context.Context) ([]ExternalConnectorsExternalActivityResult, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ExternalConnectorsExternalActivityResult collection
func (r *ExternalConnectorsExternalActivityExternalConnectorsExternalActivityResultCollectionRequest) Add(ctx context.Context, reqObj *ExternalConnectorsExternalActivityResult) (resObj *ExternalConnectorsExternalActivityResult, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}
