// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/BenHagueNZ/msgraph.go/jsonx"
)

// UnmanagedDeviceDiscoveryTask returns request builder for UnmanagedDeviceDiscoveryTask collection
func (b *DeviceAppManagementDeviceAppManagementTasksCollectionRequestBuilder) UnmanagedDeviceDiscoveryTask() *DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequestBuilder {
	bb := &DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/"
	return bb
}

// DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequestBuilder is request builder for UnmanagedDeviceDiscoveryTask collection rcn
type DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for UnmanagedDeviceDiscoveryTask collection
func (b *DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequestBuilder) Request() *DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequest {
	return &DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for UnmanagedDeviceDiscoveryTask item
func (b *DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequestBuilder) ID(id string) *UnmanagedDeviceDiscoveryTaskRequestBuilder {
	bb := &UnmanagedDeviceDiscoveryTaskRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequest is request for UnmanagedDeviceDiscoveryTask collection
type DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for UnmanagedDeviceDiscoveryTask collection
func (r *DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]UnmanagedDeviceDiscoveryTask, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []UnmanagedDeviceDiscoveryTask
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []UnmanagedDeviceDiscoveryTask
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for UnmanagedDeviceDiscoveryTask collection, max N pages
func (r *DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequest) GetN(ctx context.Context, n int) ([]UnmanagedDeviceDiscoveryTask, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for UnmanagedDeviceDiscoveryTask collection
func (r *DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequest) Get(ctx context.Context) ([]UnmanagedDeviceDiscoveryTask, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for UnmanagedDeviceDiscoveryTask collection
func (r *DeviceAppManagementDeviceAppManagementTasksCollectionUnmanagedDeviceDiscoveryTaskCollectionRequest) Add(ctx context.Context, reqObj *UnmanagedDeviceDiscoveryTask) (resObj *UnmanagedDeviceDiscoveryTask, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}
