// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// PartnerTenantType undocumented
type PartnerTenantType string

const (
	// PartnerTenantTypeVMicrosoftSupport undocumented
	PartnerTenantTypeVMicrosoftSupport PartnerTenantType = "microsoftSupport"
	// PartnerTenantTypeVSyndicatePartner undocumented
	PartnerTenantTypeVSyndicatePartner PartnerTenantType = "syndicatePartner"
	// PartnerTenantTypeVBreadthPartner undocumented
	PartnerTenantTypeVBreadthPartner PartnerTenantType = "breadthPartner"
	// PartnerTenantTypeVBreadthPartnerDelegatedAdmin undocumented
	PartnerTenantTypeVBreadthPartnerDelegatedAdmin PartnerTenantType = "breadthPartnerDelegatedAdmin"
	// PartnerTenantTypeVResellerPartnerDelegatedAdmin undocumented
	PartnerTenantTypeVResellerPartnerDelegatedAdmin PartnerTenantType = "resellerPartnerDelegatedAdmin"
	// PartnerTenantTypeVValueAddedResellerPartnerDelegatedAdmin undocumented
	PartnerTenantTypeVValueAddedResellerPartnerDelegatedAdmin PartnerTenantType = "valueAddedResellerPartnerDelegatedAdmin"
	// PartnerTenantTypeVUnknownFutureValue undocumented
	PartnerTenantTypeVUnknownFutureValue PartnerTenantType = "unknownFutureValue"
)

var (
	// PartnerTenantTypePMicrosoftSupport is a pointer to PartnerTenantTypeVMicrosoftSupport
	PartnerTenantTypePMicrosoftSupport = &_PartnerTenantTypePMicrosoftSupport
	// PartnerTenantTypePSyndicatePartner is a pointer to PartnerTenantTypeVSyndicatePartner
	PartnerTenantTypePSyndicatePartner = &_PartnerTenantTypePSyndicatePartner
	// PartnerTenantTypePBreadthPartner is a pointer to PartnerTenantTypeVBreadthPartner
	PartnerTenantTypePBreadthPartner = &_PartnerTenantTypePBreadthPartner
	// PartnerTenantTypePBreadthPartnerDelegatedAdmin is a pointer to PartnerTenantTypeVBreadthPartnerDelegatedAdmin
	PartnerTenantTypePBreadthPartnerDelegatedAdmin = &_PartnerTenantTypePBreadthPartnerDelegatedAdmin
	// PartnerTenantTypePResellerPartnerDelegatedAdmin is a pointer to PartnerTenantTypeVResellerPartnerDelegatedAdmin
	PartnerTenantTypePResellerPartnerDelegatedAdmin = &_PartnerTenantTypePResellerPartnerDelegatedAdmin
	// PartnerTenantTypePValueAddedResellerPartnerDelegatedAdmin is a pointer to PartnerTenantTypeVValueAddedResellerPartnerDelegatedAdmin
	PartnerTenantTypePValueAddedResellerPartnerDelegatedAdmin = &_PartnerTenantTypePValueAddedResellerPartnerDelegatedAdmin
	// PartnerTenantTypePUnknownFutureValue is a pointer to PartnerTenantTypeVUnknownFutureValue
	PartnerTenantTypePUnknownFutureValue = &_PartnerTenantTypePUnknownFutureValue
)

var (
	_PartnerTenantTypePMicrosoftSupport                        = PartnerTenantTypeVMicrosoftSupport
	_PartnerTenantTypePSyndicatePartner                        = PartnerTenantTypeVSyndicatePartner
	_PartnerTenantTypePBreadthPartner                          = PartnerTenantTypeVBreadthPartner
	_PartnerTenantTypePBreadthPartnerDelegatedAdmin            = PartnerTenantTypeVBreadthPartnerDelegatedAdmin
	_PartnerTenantTypePResellerPartnerDelegatedAdmin           = PartnerTenantTypeVResellerPartnerDelegatedAdmin
	_PartnerTenantTypePValueAddedResellerPartnerDelegatedAdmin = PartnerTenantTypeVValueAddedResellerPartnerDelegatedAdmin
	_PartnerTenantTypePUnknownFutureValue                      = PartnerTenantTypeVUnknownFutureValue
)
