// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// PrivilegedAccessGroupAssignmentType undocumented
type PrivilegedAccessGroupAssignmentType string

const (
	// PrivilegedAccessGroupAssignmentTypeVAssigned undocumented
	PrivilegedAccessGroupAssignmentTypeVAssigned PrivilegedAccessGroupAssignmentType = "assigned"
	// PrivilegedAccessGroupAssignmentTypeVActivated undocumented
	PrivilegedAccessGroupAssignmentTypeVActivated PrivilegedAccessGroupAssignmentType = "activated"
	// PrivilegedAccessGroupAssignmentTypeVUnknownFutureValue undocumented
	PrivilegedAccessGroupAssignmentTypeVUnknownFutureValue PrivilegedAccessGroupAssignmentType = "unknownFutureValue"
)

var (
	// PrivilegedAccessGroupAssignmentTypePAssigned is a pointer to PrivilegedAccessGroupAssignmentTypeVAssigned
	PrivilegedAccessGroupAssignmentTypePAssigned = &_PrivilegedAccessGroupAssignmentTypePAssigned
	// PrivilegedAccessGroupAssignmentTypePActivated is a pointer to PrivilegedAccessGroupAssignmentTypeVActivated
	PrivilegedAccessGroupAssignmentTypePActivated = &_PrivilegedAccessGroupAssignmentTypePActivated
	// PrivilegedAccessGroupAssignmentTypePUnknownFutureValue is a pointer to PrivilegedAccessGroupAssignmentTypeVUnknownFutureValue
	PrivilegedAccessGroupAssignmentTypePUnknownFutureValue = &_PrivilegedAccessGroupAssignmentTypePUnknownFutureValue
)

var (
	_PrivilegedAccessGroupAssignmentTypePAssigned           = PrivilegedAccessGroupAssignmentTypeVAssigned
	_PrivilegedAccessGroupAssignmentTypePActivated          = PrivilegedAccessGroupAssignmentTypeVActivated
	_PrivilegedAccessGroupAssignmentTypePUnknownFutureValue = PrivilegedAccessGroupAssignmentTypeVUnknownFutureValue
)

// PrivilegedAccessGroupMemberType undocumented
type PrivilegedAccessGroupMemberType string

const (
	// PrivilegedAccessGroupMemberTypeVDirect undocumented
	PrivilegedAccessGroupMemberTypeVDirect PrivilegedAccessGroupMemberType = "direct"
	// PrivilegedAccessGroupMemberTypeVGroup undocumented
	PrivilegedAccessGroupMemberTypeVGroup PrivilegedAccessGroupMemberType = "group"
	// PrivilegedAccessGroupMemberTypeVUnknownFutureValue undocumented
	PrivilegedAccessGroupMemberTypeVUnknownFutureValue PrivilegedAccessGroupMemberType = "unknownFutureValue"
)

var (
	// PrivilegedAccessGroupMemberTypePDirect is a pointer to PrivilegedAccessGroupMemberTypeVDirect
	PrivilegedAccessGroupMemberTypePDirect = &_PrivilegedAccessGroupMemberTypePDirect
	// PrivilegedAccessGroupMemberTypePGroup is a pointer to PrivilegedAccessGroupMemberTypeVGroup
	PrivilegedAccessGroupMemberTypePGroup = &_PrivilegedAccessGroupMemberTypePGroup
	// PrivilegedAccessGroupMemberTypePUnknownFutureValue is a pointer to PrivilegedAccessGroupMemberTypeVUnknownFutureValue
	PrivilegedAccessGroupMemberTypePUnknownFutureValue = &_PrivilegedAccessGroupMemberTypePUnknownFutureValue
)

var (
	_PrivilegedAccessGroupMemberTypePDirect             = PrivilegedAccessGroupMemberTypeVDirect
	_PrivilegedAccessGroupMemberTypePGroup              = PrivilegedAccessGroupMemberTypeVGroup
	_PrivilegedAccessGroupMemberTypePUnknownFutureValue = PrivilegedAccessGroupMemberTypeVUnknownFutureValue
)

// PrivilegedAccessGroupRelationships undocumented
type PrivilegedAccessGroupRelationships string

const (
	// PrivilegedAccessGroupRelationshipsVOwner undocumented
	PrivilegedAccessGroupRelationshipsVOwner PrivilegedAccessGroupRelationships = "owner"
	// PrivilegedAccessGroupRelationshipsVMember undocumented
	PrivilegedAccessGroupRelationshipsVMember PrivilegedAccessGroupRelationships = "member"
	// PrivilegedAccessGroupRelationshipsVUnknownFutureValue undocumented
	PrivilegedAccessGroupRelationshipsVUnknownFutureValue PrivilegedAccessGroupRelationships = "unknownFutureValue"
)

var (
	// PrivilegedAccessGroupRelationshipsPOwner is a pointer to PrivilegedAccessGroupRelationshipsVOwner
	PrivilegedAccessGroupRelationshipsPOwner = &_PrivilegedAccessGroupRelationshipsPOwner
	// PrivilegedAccessGroupRelationshipsPMember is a pointer to PrivilegedAccessGroupRelationshipsVMember
	PrivilegedAccessGroupRelationshipsPMember = &_PrivilegedAccessGroupRelationshipsPMember
	// PrivilegedAccessGroupRelationshipsPUnknownFutureValue is a pointer to PrivilegedAccessGroupRelationshipsVUnknownFutureValue
	PrivilegedAccessGroupRelationshipsPUnknownFutureValue = &_PrivilegedAccessGroupRelationshipsPUnknownFutureValue
)

var (
	_PrivilegedAccessGroupRelationshipsPOwner              = PrivilegedAccessGroupRelationshipsVOwner
	_PrivilegedAccessGroupRelationshipsPMember             = PrivilegedAccessGroupRelationshipsVMember
	_PrivilegedAccessGroupRelationshipsPUnknownFutureValue = PrivilegedAccessGroupRelationshipsVUnknownFutureValue
)
