// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// SearchAlterationType undocumented
type SearchAlterationType string

const (
	// SearchAlterationTypeVSuggestion undocumented
	SearchAlterationTypeVSuggestion SearchAlterationType = "suggestion"
	// SearchAlterationTypeVModification undocumented
	SearchAlterationTypeVModification SearchAlterationType = "modification"
	// SearchAlterationTypeVUnknownFutureValue undocumented
	SearchAlterationTypeVUnknownFutureValue SearchAlterationType = "unknownFutureValue"
)

var (
	// SearchAlterationTypePSuggestion is a pointer to SearchAlterationTypeVSuggestion
	SearchAlterationTypePSuggestion = &_SearchAlterationTypePSuggestion
	// SearchAlterationTypePModification is a pointer to SearchAlterationTypeVModification
	SearchAlterationTypePModification = &_SearchAlterationTypePModification
	// SearchAlterationTypePUnknownFutureValue is a pointer to SearchAlterationTypeVUnknownFutureValue
	SearchAlterationTypePUnknownFutureValue = &_SearchAlterationTypePUnknownFutureValue
)

var (
	_SearchAlterationTypePSuggestion         = SearchAlterationTypeVSuggestion
	_SearchAlterationTypePModification       = SearchAlterationTypeVModification
	_SearchAlterationTypePUnknownFutureValue = SearchAlterationTypeVUnknownFutureValue
)

// SearchContent undocumented
type SearchContent string

const (
	// SearchContentVSharedContent undocumented
	SearchContentVSharedContent SearchContent = "sharedContent"
	// SearchContentVPrivateContent undocumented
	SearchContentVPrivateContent SearchContent = "privateContent"
	// SearchContentVUnknownFutureValue undocumented
	SearchContentVUnknownFutureValue SearchContent = "unknownFutureValue"
)

var (
	// SearchContentPSharedContent is a pointer to SearchContentVSharedContent
	SearchContentPSharedContent = &_SearchContentPSharedContent
	// SearchContentPPrivateContent is a pointer to SearchContentVPrivateContent
	SearchContentPPrivateContent = &_SearchContentPPrivateContent
	// SearchContentPUnknownFutureValue is a pointer to SearchContentVUnknownFutureValue
	SearchContentPUnknownFutureValue = &_SearchContentPUnknownFutureValue
)

var (
	_SearchContentPSharedContent      = SearchContentVSharedContent
	_SearchContentPPrivateContent     = SearchContentVPrivateContent
	_SearchContentPUnknownFutureValue = SearchContentVUnknownFutureValue
)

// SearchAnswerState undocumented
type SearchAnswerState string

const (
	// SearchAnswerStateVPublished undocumented
	SearchAnswerStateVPublished SearchAnswerState = "published"
	// SearchAnswerStateVDraft undocumented
	SearchAnswerStateVDraft SearchAnswerState = "draft"
	// SearchAnswerStateVExcluded undocumented
	SearchAnswerStateVExcluded SearchAnswerState = "excluded"
	// SearchAnswerStateVUnknownFutureValue undocumented
	SearchAnswerStateVUnknownFutureValue SearchAnswerState = "unknownFutureValue"
)

var (
	// SearchAnswerStatePPublished is a pointer to SearchAnswerStateVPublished
	SearchAnswerStatePPublished = &_SearchAnswerStatePPublished
	// SearchAnswerStatePDraft is a pointer to SearchAnswerStateVDraft
	SearchAnswerStatePDraft = &_SearchAnswerStatePDraft
	// SearchAnswerStatePExcluded is a pointer to SearchAnswerStateVExcluded
	SearchAnswerStatePExcluded = &_SearchAnswerStatePExcluded
	// SearchAnswerStatePUnknownFutureValue is a pointer to SearchAnswerStateVUnknownFutureValue
	SearchAnswerStatePUnknownFutureValue = &_SearchAnswerStatePUnknownFutureValue
)

var (
	_SearchAnswerStatePPublished          = SearchAnswerStateVPublished
	_SearchAnswerStatePDraft              = SearchAnswerStateVDraft
	_SearchAnswerStatePExcluded           = SearchAnswerStateVExcluded
	_SearchAnswerStatePUnknownFutureValue = SearchAnswerStateVUnknownFutureValue
)
