// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// HorizontalSection undocumented
type HorizontalSection struct {
	// Entity is the base model of HorizontalSection
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// Emphasis undocumented
	Emphasis *SectionEmphasisType `json:"emphasis,omitempty"`
	// Layout undocumented
	Layout *HorizontalSectionLayoutType `json:"layout,omitempty"`
	// Columns undocumented
	Columns []HorizontalSectionColumn `json:"columns,omitempty"`
}

func NewHorizontalSection() (*HorizontalSection, error) {
	newHorizontalSection := &HorizontalSection{
		ODataType: "#microsoft.graph.HorizontalSection",
	}
	return newHorizontalSection, nil
}

// HorizontalSectionColumn undocumented
type HorizontalSectionColumn struct {
	// Entity is the base model of HorizontalSectionColumn
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// Width undocumented
	Width *int `json:"width,omitempty"`
	// Webparts undocumented
	Webparts []WebPart `json:"webparts,omitempty"`
}

func NewHorizontalSectionColumn() (*HorizontalSectionColumn, error) {
	newHorizontalSectionColumn := &HorizontalSectionColumn{
		ODataType: "#microsoft.graph.HorizontalSectionColumn",
	}
	return newHorizontalSectionColumn, nil
}
