
// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph


// Printer undocumented
type Printer struct {
    // PrinterBase is the base model of Printer
    PrinterBase
    // AcceptingJobs undocumented
    AcceptingJobs *bool `json:"acceptingJobs,omitempty"`
    // HasPhysicalDevice undocumented
    HasPhysicalDevice *bool `json:"hasPhysicalDevice,omitempty"`
    // IsShared undocumented
    IsShared *bool `json:"isShared,omitempty"`
    // LastSeenDateTime undocumented
    LastSeenDateTime *time.Time `json:"lastSeenDateTime,omitempty"`
    // RegisteredDateTime undocumented
    RegisteredDateTime *time.Time `json:"registeredDateTime,omitempty"`
    // Connectors undocumented
    Connectors []PrintConnector `json:"connectors,omitempty"`
    // Share undocumented
    Share *PrinterShare `json:"share,omitempty"`
    // Shares undocumented
    Shares []PrinterShare `json:"shares,omitempty"`
    // TaskTriggers undocumented
    TaskTriggers []PrintTaskTrigger `json:"taskTriggers,omitempty"`
}

// PrinterBase undocumented
type PrinterBase struct {
    // Entity is the base model of PrinterBase
    Entity
    // Capabilities undocumented
    Capabilities *PrinterCapabilities `json:"capabilities,omitempty"`
    // Defaults undocumented
    Defaults *PrinterDefaults `json:"defaults,omitempty"`
    // DisplayName undocumented
    DisplayName *string `json:"displayName,omitempty"`
    // IsAcceptingJobs undocumented
    IsAcceptingJobs *bool `json:"isAcceptingJobs,omitempty"`
    // Location undocumented
    Location *PrinterLocation `json:"location,omitempty"`
    // Manufacturer undocumented
    Manufacturer *string `json:"manufacturer,omitempty"`
    // Model undocumented
    Model *string `json:"model,omitempty"`
    // Name undocumented
    Name *string `json:"name,omitempty"`
    // Status undocumented
    Status *PrinterStatus `json:"status,omitempty"`
    // Jobs undocumented
    Jobs []PrintJob `json:"jobs,omitempty"`
}

// PrinterCapabilities undocumented
type PrinterCapabilities struct {
    // Object is the base model of PrinterCapabilities
    Object
    // BottomMargins undocumented
    BottomMargins []int `json:"bottomMargins,omitempty"`
    // Collation undocumented
    Collation *bool `json:"collation,omitempty"`
    // ColorModes undocumented
    ColorModes []PrintColorMode `json:"colorModes,omitempty"`
    // ContentTypes undocumented
    ContentTypes []string `json:"contentTypes,omitempty"`
    // CopiesPerJob undocumented
    CopiesPerJob *IntegerRange `json:"copiesPerJob,omitempty"`
    // Dpis undocumented
    Dpis []int `json:"dpis,omitempty"`
    // DuplexModes undocumented
    DuplexModes []PrintDuplexMode `json:"duplexModes,omitempty"`
    // FeedDirections undocumented
    FeedDirections []PrinterFeedDirection `json:"feedDirections,omitempty"`
    // FeedOrientations undocumented
    FeedOrientations []PrinterFeedOrientation `json:"feedOrientations,omitempty"`
    // Finishings undocumented
    Finishings []PrintFinishing `json:"finishings,omitempty"`
    // InputBins undocumented
    InputBins []string `json:"inputBins,omitempty"`
    // IsColorPrintingSupported undocumented
    IsColorPrintingSupported *bool `json:"isColorPrintingSupported,omitempty"`
    // IsPageRangeSupported undocumented
    IsPageRangeSupported *bool `json:"isPageRangeSupported,omitempty"`
    // LeftMargins undocumented
    LeftMargins []int `json:"leftMargins,omitempty"`
    // MediaColors undocumented
    MediaColors []string `json:"mediaColors,omitempty"`
    // MediaSizes undocumented
    MediaSizes []string `json:"mediaSizes,omitempty"`
    // MediaTypes undocumented
    MediaTypes []string `json:"mediaTypes,omitempty"`
    // MultipageLayouts undocumented
    MultipageLayouts []PrintMultipageLayout `json:"multipageLayouts,omitempty"`
    // Orientations undocumented
    Orientations []PrintOrientation `json:"orientations,omitempty"`
    // OutputBins undocumented
    OutputBins []string `json:"outputBins,omitempty"`
    // PagesPerSheet undocumented
    PagesPerSheet []int `json:"pagesPerSheet,omitempty"`
    // Qualities undocumented
    Qualities []PrintQuality `json:"qualities,omitempty"`
    // RightMargins undocumented
    RightMargins []int `json:"rightMargins,omitempty"`
    // Scalings undocumented
    Scalings []PrintScaling `json:"scalings,omitempty"`
    // SupportedColorConfigurations undocumented
    SupportedColorConfigurations []PrintColorConfiguration `json:"supportedColorConfigurations,omitempty"`
    // SupportedCopiesPerJob undocumented
    SupportedCopiesPerJob *IntegerRange `json:"supportedCopiesPerJob,omitempty"`
    // SupportedDocumentMimeTypes undocumented
    SupportedDocumentMimeTypes []string `json:"supportedDocumentMimeTypes,omitempty"`
    // SupportedDuplexConfigurations undocumented
    SupportedDuplexConfigurations []PrintDuplexConfiguration `json:"supportedDuplexConfigurations,omitempty"`
    // SupportedFinishings undocumented
    SupportedFinishings []PrintFinishing `json:"supportedFinishings,omitempty"`
    // SupportedMediaColors undocumented
    SupportedMediaColors []string `json:"supportedMediaColors,omitempty"`
    // SupportedMediaSizes undocumented
    SupportedMediaSizes []string `json:"supportedMediaSizes,omitempty"`
    // SupportedMediaTypes undocumented
    SupportedMediaTypes []PrintMediaType `json:"supportedMediaTypes,omitempty"`
    // SupportedOrientations undocumented
    SupportedOrientations []PrintOrientation `json:"supportedOrientations,omitempty"`
    // SupportedOutputBins undocumented
    SupportedOutputBins []string `json:"supportedOutputBins,omitempty"`
    // SupportedPagesPerSheet undocumented
    SupportedPagesPerSheet *IntegerRange `json:"supportedPagesPerSheet,omitempty"`
    // SupportedPresentationDirections undocumented
    SupportedPresentationDirections []PrintPresentationDirection `json:"supportedPresentationDirections,omitempty"`
    // SupportedPrintQualities undocumented
    SupportedPrintQualities []PrintQuality `json:"supportedPrintQualities,omitempty"`
    // SupportsFitPdfToPage undocumented
    SupportsFitPdfToPage *bool `json:"supportsFitPdfToPage,omitempty"`
    // TopMargins undocumented
    TopMargins []int `json:"topMargins,omitempty"`
}

// PrinterCreateOperation undocumented
type PrinterCreateOperation struct {
    // PrintOperation is the base model of PrinterCreateOperation
    PrintOperation
    // Certificate undocumented
    Certificate *string `json:"certificate,omitempty"`
    // Printer undocumented
    Printer *Printer `json:"printer,omitempty"`
}

// PrinterDefaults undocumented
type PrinterDefaults struct {
    // Object is the base model of PrinterDefaults
    Object
    // ColorMode undocumented
    ColorMode *PrintColorMode `json:"colorMode,omitempty"`
    // ContentType undocumented
    ContentType *string `json:"contentType,omitempty"`
    // CopiesPerJob undocumented
    CopiesPerJob *int `json:"copiesPerJob,omitempty"`
    // DocumentMimeType undocumented
    DocumentMimeType *string `json:"documentMimeType,omitempty"`
    // Dpi undocumented
    Dpi *int `json:"dpi,omitempty"`
    // DuplexConfiguration undocumented
    DuplexConfiguration *PrintDuplexConfiguration `json:"duplexConfiguration,omitempty"`
    // DuplexMode undocumented
    DuplexMode *PrintDuplexMode `json:"duplexMode,omitempty"`
    // Finishings undocumented
    Finishings []PrintFinishing `json:"finishings,omitempty"`
    // FitPdfToPage undocumented
    FitPdfToPage *bool `json:"fitPdfToPage,omitempty"`
    // InputBin undocumented
    InputBin *string `json:"inputBin,omitempty"`
    // MediaColor undocumented
    MediaColor *string `json:"mediaColor,omitempty"`
    // MediaSize undocumented
    MediaSize *string `json:"mediaSize,omitempty"`
    // MediaType undocumented
    MediaType *string `json:"mediaType,omitempty"`
    // MultipageLayout undocumented
    MultipageLayout *PrintMultipageLayout `json:"multipageLayout,omitempty"`
    // Orientation undocumented
    Orientation *PrintOrientation `json:"orientation,omitempty"`
    // OutputBin undocumented
    OutputBin *string `json:"outputBin,omitempty"`
    // PagesPerSheet undocumented
    PagesPerSheet *int `json:"pagesPerSheet,omitempty"`
    // PdfFitToPage undocumented
    PdfFitToPage *bool `json:"pdfFitToPage,omitempty"`
    // PresentationDirection undocumented
    PresentationDirection *PrintPresentationDirection `json:"presentationDirection,omitempty"`
    // PrintColorConfiguration undocumented
    PrintColorConfiguration *PrintColorConfiguration `json:"printColorConfiguration,omitempty"`
    // PrintQuality undocumented
    PrintQuality *PrintQuality `json:"printQuality,omitempty"`
    // Quality undocumented
    Quality *PrintQuality `json:"quality,omitempty"`
    // Scaling undocumented
    Scaling *PrintScaling `json:"scaling,omitempty"`
}

// PrinterDocumentConfiguration undocumented
type PrinterDocumentConfiguration struct {
    // Object is the base model of PrinterDocumentConfiguration
    Object
    // Collate undocumented
    Collate *bool `json:"collate,omitempty"`
    // ColorMode undocumented
    ColorMode *PrintColorMode `json:"colorMode,omitempty"`
    // Copies undocumented
    Copies *int `json:"copies,omitempty"`
    // Dpi undocumented
    Dpi *int `json:"dpi,omitempty"`
    // DuplexMode undocumented
    DuplexMode *PrintDuplexMode `json:"duplexMode,omitempty"`
    // FeedDirection undocumented
    FeedDirection *PrinterFeedDirection `json:"feedDirection,omitempty"`
    // FeedOrientation undocumented
    FeedOrientation *PrinterFeedOrientation `json:"feedOrientation,omitempty"`
    // Finishings undocumented
    Finishings []PrintFinishing `json:"finishings,omitempty"`
    // FitPdfToPage undocumented
    FitPdfToPage *bool `json:"fitPdfToPage,omitempty"`
    // InputBin undocumented
    InputBin *string `json:"inputBin,omitempty"`
    // Margin undocumented
    Margin *PrintMargin `json:"margin,omitempty"`
    // MediaSize undocumented
    MediaSize *string `json:"mediaSize,omitempty"`
    // MediaType undocumented
    MediaType *string `json:"mediaType,omitempty"`
    // MultipageLayout undocumented
    MultipageLayout *PrintMultipageLayout `json:"multipageLayout,omitempty"`
    // Orientation undocumented
    Orientation *PrintOrientation `json:"orientation,omitempty"`
    // OutputBin undocumented
    OutputBin *string `json:"outputBin,omitempty"`
    // PageRanges undocumented
    PageRanges []IntegerRange `json:"pageRanges,omitempty"`
    // PagesPerSheet undocumented
    PagesPerSheet *int `json:"pagesPerSheet,omitempty"`
    // Quality undocumented
    Quality *PrintQuality `json:"quality,omitempty"`
    // Scaling undocumented
    Scaling *PrintScaling `json:"scaling,omitempty"`
}

// PrinterLocation undocumented
type PrinterLocation struct {
    // Object is the base model of PrinterLocation
    Object
    // AltitudeInMeters undocumented
    AltitudeInMeters *int `json:"altitudeInMeters,omitempty"`
    // Building undocumented
    Building *string `json:"building,omitempty"`
    // City undocumented
    City *string `json:"city,omitempty"`
    // CountryOrRegion undocumented
    CountryOrRegion *string `json:"countryOrRegion,omitempty"`
    // Floor undocumented
    Floor *string `json:"floor,omitempty"`
    // FloorDescription undocumented
    FloorDescription *string `json:"floorDescription,omitempty"`
    // FloorNumber undocumented
    FloorNumber *int `json:"floorNumber,omitempty"`
    // Latitude undocumented
    Latitude *float64 `json:"latitude,omitempty"`
    // Longitude undocumented
    Longitude *float64 `json:"longitude,omitempty"`
    // Organization undocumented
    Organization []string `json:"organization,omitempty"`
    // PostalCode undocumented
    PostalCode *string `json:"postalCode,omitempty"`
    // RoomDescription undocumented
    RoomDescription *string `json:"roomDescription,omitempty"`
    // RoomName undocumented
    RoomName *string `json:"roomName,omitempty"`
    // RoomNumber undocumented
    RoomNumber *int `json:"roomNumber,omitempty"`
    // Site undocumented
    Site *string `json:"site,omitempty"`
    // StateOrProvince undocumented
    StateOrProvince *string `json:"stateOrProvince,omitempty"`
    // StreetAddress undocumented
    StreetAddress *string `json:"streetAddress,omitempty"`
    // Subdivision undocumented
    Subdivision []string `json:"subdivision,omitempty"`
    // Subunit undocumented
    Subunit []string `json:"subunit,omitempty"`
}

// PrinterShare undocumented
type PrinterShare struct {
    // PrinterBase is the base model of PrinterShare
    PrinterBase
    // AllowAllUsers undocumented
    AllowAllUsers *bool `json:"allowAllUsers,omitempty"`
    // CreatedDateTime undocumented
    CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
    // ViewPoint undocumented
    ViewPoint *PrinterShareViewpoint `json:"viewPoint,omitempty"`
    // AllowedGroups undocumented
    AllowedGroups []Group `json:"allowedGroups,omitempty"`
    // AllowedUsers undocumented
    AllowedUsers []User `json:"allowedUsers,omitempty"`
    // Printer undocumented
    Printer *Printer `json:"printer,omitempty"`
}

// PrinterShareViewpoint undocumented
type PrinterShareViewpoint struct {
    // Object is the base model of PrinterShareViewpoint
    Object
    // LastUsedDateTime undocumented
    LastUsedDateTime *time.Time `json:"lastUsedDateTime,omitempty"`
}

// PrinterStatus undocumented
type PrinterStatus struct {
    // Object is the base model of PrinterStatus
    Object
    // Description undocumented
    Description *string `json:"description,omitempty"`
    // Details undocumented
    Details []PrinterProcessingStateDetail `json:"details,omitempty"`
    // ProcessingState undocumented
    ProcessingState *PrinterProcessingState `json:"processingState,omitempty"`
    // ProcessingStateDescription undocumented
    ProcessingStateDescription *string `json:"processingStateDescription,omitempty"`
    // ProcessingStateReasons undocumented
    ProcessingStateReasons []PrinterProcessingStateReason `json:"processingStateReasons,omitempty"`
    // State undocumented
    State *PrinterProcessingState `json:"state,omitempty"`
}

// PrinterUsageSummary undocumented
type PrinterUsageSummary struct {
    // Object is the base model of PrinterUsageSummary
    Object
    // CompletedJobCount undocumented
    CompletedJobCount *int `json:"completedJobCount,omitempty"`
    // IncompleteJobCount undocumented
    IncompleteJobCount *int `json:"incompleteJobCount,omitempty"`
    // PrinterDisplayName undocumented
    PrinterDisplayName *string `json:"printerDisplayName,omitempty"`
    // PrinterID undocumented
    PrinterID *string `json:"printerId,omitempty"`
    // PrinterManufacturer undocumented
    PrinterManufacturer *string `json:"printerManufacturer,omitempty"`
    // PrinterModel undocumented
    PrinterModel *string `json:"printerModel,omitempty"`
    // Printer undocumented
    Printer *DirectoryObject `json:"printer,omitempty"`
}
