// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Workflow undocumented
type Workflow struct {
	// IdentityGovernance_workflowBase is the base model of Workflow
	IdentityGovernance_workflowBase
	// DeletedDateTime undocumented
	DeletedDateTime *time.Time `json:"deletedDateTime,omitempty"`
	// ID undocumented
	ID *string `json:"id,omitempty"`
	// NextScheduleRunDateTime undocumented
	NextScheduleRunDateTime *time.Time `json:"nextScheduleRunDateTime,omitempty"`
	// Version undocumented
	Version *int `json:"version,omitempty"`
	// ExecutionScope undocumented
	ExecutionScope []User `json:"executionScope,omitempty"`
	// Runs undocumented
	Runs []IdentityGovernance_run `json:"runs,omitempty"`
	// TaskReports undocumented
	TaskReports []IdentityGovernance_taskReport `json:"taskReports,omitempty"`
	// UserProcessingResults undocumented
	UserProcessingResults []IdentityGovernance_userProcessingResult `json:"userProcessingResults,omitempty"`
	// Versions undocumented
	Versions []IdentityGovernance_workflowVersion `json:"versions,omitempty"`
}

// WorkflowBase undocumented
type WorkflowBase struct {
	// Object is the base model of WorkflowBase
	Object
	// Category undocumented
	Category *IdentityGovernance_lifecycleWorkflowCategory `json:"category,omitempty"`
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// ExecutionConditions undocumented
	ExecutionConditions *IdentityGovernance_workflowExecutionConditions `json:"executionConditions,omitempty"`
	// IsEnabled undocumented
	IsEnabled *bool `json:"isEnabled,omitempty"`
	// IsSchedulingEnabled undocumented
	IsSchedulingEnabled *bool `json:"isSchedulingEnabled,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// CreatedBy undocumented
	CreatedBy *User `json:"createdBy,omitempty"`
	// LastModifiedBy undocumented
	LastModifiedBy *User `json:"lastModifiedBy,omitempty"`
	// Tasks undocumented
	Tasks []IdentityGovernance_task `json:"tasks,omitempty"`
}

// WorkflowExecutionConditions undocumented
type WorkflowExecutionConditions struct {
	// Object is the base model of WorkflowExecutionConditions
	Object
}

// WorkflowExecutionTrigger undocumented
type WorkflowExecutionTrigger struct {
	// Object is the base model of WorkflowExecutionTrigger
	Object
}

// WorkflowTemplate undocumented
type WorkflowTemplate struct {
	// Entity is the base model of WorkflowTemplate
	Entity
	// Category undocumented
	Category *IdentityGovernance_lifecycleWorkflowCategory `json:"category,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// ExecutionConditions undocumented
	ExecutionConditions *IdentityGovernance_workflowExecutionConditions `json:"executionConditions,omitempty"`
	// Tasks undocumented
	Tasks []IdentityGovernance_task `json:"tasks,omitempty"`
}

// WorkflowVersion undocumented
type WorkflowVersion struct {
	// IdentityGovernance_workflowBase is the base model of WorkflowVersion
	IdentityGovernance_workflowBase
	// VersionNumber undocumented
	VersionNumber *int `json:"versionNumber,omitempty"`
}
