// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// Parameter undocumented
type Parameter struct {
	// Object is the base model of Parameter
	Object
	// Name undocumented
	Name *string `json:"name,omitempty"`
	// Values undocumented
	Values []string `json:"values,omitempty"`
	// ValueType undocumented
	ValueType *IdentityGovernance_valueType `json:"valueType,omitempty"`
}
