// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// Drive undocumented
type Drive struct {
	// BaseItem is the base model of Drive
	BaseItem

	ODataType string `json:"@odata.type,omitempty"`
	// DriveType undocumented
	DriveType *string `json:"driveType,omitempty"`
	// Owner undocumented
	Owner *IdentitySet `json:"owner,omitempty"`
	// Quota undocumented
	Quota *Quota `json:"quota,omitempty"`
	// SharePointIDs undocumented
	SharePointIDs *SharepointIDs `json:"sharePointIds,omitempty"`
	// System undocumented
	System *SystemFacet `json:"system,omitempty"`
	// Activities undocumented
	Activities []ItemActivityOLD `json:"activities,omitempty"`
	// Bundles undocumented
	Bundles []DriveItem `json:"bundles,omitempty"`
	// Following undocumented
	Following []DriveItem `json:"following,omitempty"`
	// Items undocumented
	Items []DriveItem `json:"items,omitempty"`
	// List undocumented
	List *List `json:"list,omitempty"`
	// Root undocumented
	Root *DriveItem `json:"root,omitempty"`
	// Special undocumented
	Special []DriveItem `json:"special,omitempty"`
}

func NewDrive() (*Drive, error) {
	newDrive := &Drive{
		ODataType: "#microsoft.graph.Drive",
	}
	return newDrive, nil
}

// DriveItem undocumented
type DriveItem struct {
	// BaseItem is the base model of DriveItem
	BaseItem

	ODataType string `json:"@odata.type,omitempty"`
	// Audio undocumented
	Audio *Audio `json:"audio,omitempty"`
	// Bundle undocumented
	Bundle *Bundle `json:"bundle,omitempty"`
	// Content undocumented
	Content *Stream `json:"content,omitempty"`
	// CTag undocumented
	CTag *string `json:"cTag,omitempty"`
	// Deleted undocumented
	Deleted *Deleted `json:"deleted,omitempty"`
	// File undocumented
	File *File `json:"file,omitempty"`
	// FileSystemInfo undocumented
	FileSystemInfo *FileSystemInfo `json:"fileSystemInfo,omitempty"`
	// Folder undocumented
	Folder *Folder `json:"folder,omitempty"`
	// Image undocumented
	Image *Image `json:"image,omitempty"`
	// Location undocumented
	Location *GeoCoordinates `json:"location,omitempty"`
	// Malware undocumented
	Malware *Malware `json:"malware,omitempty"`
	// Media undocumented
	Media *Media `json:"media,omitempty"`
	// Package undocumented
	Package *Package `json:"package,omitempty"`
	// PendingOperations undocumented
	PendingOperations *PendingOperations `json:"pendingOperations,omitempty"`
	// Photo undocumented
	Photo *Photo `json:"photo,omitempty"`
	// Publication undocumented
	Publication *PublicationFacet `json:"publication,omitempty"`
	// RemoteItem undocumented
	RemoteItem *RemoteItem `json:"remoteItem,omitempty"`
	// Root undocumented
	Root *Root `json:"root,omitempty"`
	// SearchResult undocumented
	SearchResult *SearchResult `json:"searchResult,omitempty"`
	// Shared undocumented
	Shared *Shared `json:"shared,omitempty"`
	// SharepointIDs undocumented
	SharepointIDs *SharepointIDs `json:"sharepointIds,omitempty"`
	// Size undocumented
	Size *int `json:"size,omitempty"`
	// Source undocumented
	Source *DriveItemSource `json:"source,omitempty"`
	// SpecialFolder undocumented
	SpecialFolder *SpecialFolder `json:"specialFolder,omitempty"`
	// Video undocumented
	Video *Video `json:"video,omitempty"`
	// WebDavURL undocumented
	WebDavURL *string `json:"webDavUrl,omitempty"`
	// Workbook undocumented
	Workbook *Workbook `json:"workbook,omitempty"`
	// Activities undocumented
	Activities []ItemActivityOLD `json:"activities,omitempty"`
	// Analytics undocumented
	Analytics *ItemAnalytics `json:"analytics,omitempty"`
	// Children undocumented
	Children []DriveItem `json:"children,omitempty"`
	// ListItem undocumented
	ListItem *ListItem `json:"listItem,omitempty"`
	// Permissions undocumented
	Permissions []Permission `json:"permissions,omitempty"`
	// RetentionLabel undocumented
	RetentionLabel *ItemRetentionLabel `json:"retentionLabel,omitempty"`
	// Subscriptions undocumented
	Subscriptions []Subscription `json:"subscriptions,omitempty"`
	// Thumbnails undocumented
	Thumbnails []ThumbnailSet `json:"thumbnails,omitempty"`
	// Versions undocumented
	Versions []DriveItemVersion `json:"versions,omitempty"`
}

func NewDriveItem() (*DriveItem, error) {
	newDriveItem := &DriveItem{
		ODataType: "#microsoft.graph.DriveItem",
	}
	return newDriveItem, nil
}

// DriveItemSource undocumented
type DriveItemSource struct {
	// Object is the base model of DriveItemSource
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// Application undocumented
	Application *DriveItemSourceApplication `json:"application,omitempty"`
	// ExternalID undocumented
	ExternalID *string `json:"externalId,omitempty"`
}

func NewDriveItemSource() (*DriveItemSource, error) {
	newDriveItemSource := &DriveItemSource{
		ODataType: "#microsoft.graph.DriveItemSource",
	}
	return newDriveItemSource, nil
}

// DriveItemUploadableProperties undocumented
type DriveItemUploadableProperties struct {
	// Object is the base model of DriveItemUploadableProperties
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// FileSize undocumented
	FileSize *int `json:"fileSize,omitempty"`
	// FileSystemInfo undocumented
	FileSystemInfo *FileSystemInfo `json:"fileSystemInfo,omitempty"`
	// Name undocumented
	Name *string `json:"name,omitempty"`
}

func NewDriveItemUploadableProperties() (*DriveItemUploadableProperties, error) {
	newDriveItemUploadableProperties := &DriveItemUploadableProperties{
		ODataType: "#microsoft.graph.DriveItemUploadableProperties",
	}
	return newDriveItemUploadableProperties, nil
}

// DriveItemVersion undocumented
type DriveItemVersion struct {
	// BaseItemVersion is the base model of DriveItemVersion
	BaseItemVersion

	ODataType string `json:"@odata.type,omitempty"`
	// Content undocumented
	Content *Stream `json:"content,omitempty"`
	// Size undocumented
	Size *int `json:"size,omitempty"`
}

func NewDriveItemVersion() (*DriveItemVersion, error) {
	newDriveItemVersion := &DriveItemVersion{
		ODataType: "#microsoft.graph.DriveItemVersion",
	}
	return newDriveItemVersion, nil
}

// DriveRecipient undocumented
type DriveRecipient struct {
	// Object is the base model of DriveRecipient
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// Alias undocumented
	Alias *string `json:"alias,omitempty"`
	// Email undocumented
	Email *string `json:"email,omitempty"`
	// ObjectID undocumented
	ObjectID *string `json:"objectId,omitempty"`
}

func NewDriveRecipient() (*DriveRecipient, error) {
	newDriveRecipient := &DriveRecipient{
		ODataType: "#microsoft.graph.DriveRecipient",
	}
	return newDriveRecipient, nil
}
