
// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph


// ConditionalAccessAllExternalTenants undocumented
type ConditionalAccessAllExternalTenants struct {
    // ConditionalAccessExternalTenants is the base model of ConditionalAccessAllExternalTenants
    ConditionalAccessExternalTenants
}

// ConditionalAccessApplications undocumented
type ConditionalAccessApplications struct {
    // Object is the base model of ConditionalAccessApplications
    Object
    // ApplicationFilter undocumented
    ApplicationFilter *ConditionalAccessFilter `json:"applicationFilter,omitempty"`
    // ExcludeApplications undocumented
    ExcludeApplications []string `json:"excludeApplications,omitempty"`
    // IncludeApplications undocumented
    IncludeApplications []string `json:"includeApplications,omitempty"`
    // IncludeAuthenticationContextClassReferences undocumented
    IncludeAuthenticationContextClassReferences []string `json:"includeAuthenticationContextClassReferences,omitempty"`
    // IncludeUserActions undocumented
    IncludeUserActions []string `json:"includeUserActions,omitempty"`
}

// ConditionalAccessClientApplications undocumented
type ConditionalAccessClientApplications struct {
    // Object is the base model of ConditionalAccessClientApplications
    Object
    // ExcludeServicePrincipals undocumented
    ExcludeServicePrincipals []string `json:"excludeServicePrincipals,omitempty"`
    // IncludeServicePrincipals undocumented
    IncludeServicePrincipals []string `json:"includeServicePrincipals,omitempty"`
    // ServicePrincipalFilter undocumented
    ServicePrincipalFilter *ConditionalAccessFilter `json:"servicePrincipalFilter,omitempty"`
}

// ConditionalAccessConditionSet undocumented
type ConditionalAccessConditionSet struct {
    // Object is the base model of ConditionalAccessConditionSet
    Object
    // Applications undocumented
    Applications *ConditionalAccessApplications `json:"applications,omitempty"`
    // ClientApplications undocumented
    ClientApplications *ConditionalAccessClientApplications `json:"clientApplications,omitempty"`
    // ClientAppTypes undocumented
    ClientAppTypes []ConditionalAccessClientApp `json:"clientAppTypes,omitempty"`
    // Devices undocumented
    Devices *ConditionalAccessDevices `json:"devices,omitempty"`
    // DeviceStates undocumented
    DeviceStates *ConditionalAccessDeviceStates `json:"deviceStates,omitempty"`
    // Locations undocumented
    Locations *ConditionalAccessLocations `json:"locations,omitempty"`
    // Platforms undocumented
    Platforms *ConditionalAccessPlatforms `json:"platforms,omitempty"`
    // ServicePrincipalRiskLevels undocumented
    ServicePrincipalRiskLevels []RiskLevel `json:"servicePrincipalRiskLevels,omitempty"`
    // SignInRiskLevels undocumented
    SignInRiskLevels []RiskLevel `json:"signInRiskLevels,omitempty"`
    // UserRiskLevels undocumented
    UserRiskLevels []RiskLevel `json:"userRiskLevels,omitempty"`
    // Users undocumented
    Users *ConditionalAccessUsers `json:"users,omitempty"`
}

// ConditionalAccessDeviceStates undocumented
type ConditionalAccessDeviceStates struct {
    // Object is the base model of ConditionalAccessDeviceStates
    Object
    // ExcludeStates undocumented
    ExcludeStates []string `json:"excludeStates,omitempty"`
    // IncludeStates undocumented
    IncludeStates []string `json:"includeStates,omitempty"`
}

// ConditionalAccessDevices undocumented
type ConditionalAccessDevices struct {
    // Object is the base model of ConditionalAccessDevices
    Object
    // DeviceFilter undocumented
    DeviceFilter *ConditionalAccessFilter `json:"deviceFilter,omitempty"`
    // ExcludeDevices undocumented
    ExcludeDevices []string `json:"excludeDevices,omitempty"`
    // ExcludeDeviceStates undocumented
    ExcludeDeviceStates []string `json:"excludeDeviceStates,omitempty"`
    // IncludeDevices undocumented
    IncludeDevices []string `json:"includeDevices,omitempty"`
    // IncludeDeviceStates undocumented
    IncludeDeviceStates []string `json:"includeDeviceStates,omitempty"`
}

// ConditionalAccessEnumeratedExternalTenants undocumented
type ConditionalAccessEnumeratedExternalTenants struct {
    // ConditionalAccessExternalTenants is the base model of ConditionalAccessEnumeratedExternalTenants
    ConditionalAccessExternalTenants
    // Members undocumented
    Members []string `json:"members,omitempty"`
}

// ConditionalAccessExternalTenants undocumented
type ConditionalAccessExternalTenants struct {
    // Object is the base model of ConditionalAccessExternalTenants
    Object
    // MembershipKind undocumented
    MembershipKind *ConditionalAccessExternalTenantsMembershipKind `json:"membershipKind,omitempty"`
}

// ConditionalAccessFilter undocumented
type ConditionalAccessFilter struct {
    // Object is the base model of ConditionalAccessFilter
    Object
    // Mode undocumented
    Mode *FilterMode `json:"mode,omitempty"`
    // Rule undocumented
    Rule *string `json:"rule,omitempty"`
}

// ConditionalAccessGrantControls undocumented
type ConditionalAccessGrantControls struct {
    // Object is the base model of ConditionalAccessGrantControls
    Object
    // BuiltInControls undocumented
    BuiltInControls []ConditionalAccessGrantControl `json:"builtInControls,omitempty"`
    // CustomAuthenticationFactors undocumented
    CustomAuthenticationFactors []string `json:"customAuthenticationFactors,omitempty"`
    // Operator undocumented
    Operator *string `json:"operator,omitempty"`
    // TermsOfUse undocumented
    TermsOfUse []string `json:"termsOfUse,omitempty"`
    // AuthenticationStrength undocumented
    AuthenticationStrength *AuthenticationStrengthPolicy `json:"authenticationStrength,omitempty"`
}

// ConditionalAccessGuestsOrExternalUsers undocumented
type ConditionalAccessGuestsOrExternalUsers struct {
    // Object is the base model of ConditionalAccessGuestsOrExternalUsers
    Object
    // ExternalTenants undocumented
    ExternalTenants *ConditionalAccessExternalTenants `json:"externalTenants,omitempty"`
    // GuestOrExternalUserTypes undocumented
    GuestOrExternalUserTypes *ConditionalAccessGuestOrExternalUserTypes `json:"guestOrExternalUserTypes,omitempty"`
}

// ConditionalAccessLocations undocumented
type ConditionalAccessLocations struct {
    // Object is the base model of ConditionalAccessLocations
    Object
    // ExcludeLocations undocumented
    ExcludeLocations []string `json:"excludeLocations,omitempty"`
    // IncludeLocations undocumented
    IncludeLocations []string `json:"includeLocations,omitempty"`
}

// ConditionalAccessPlatforms undocumented
type ConditionalAccessPlatforms struct {
    // Object is the base model of ConditionalAccessPlatforms
    Object
    // ExcludePlatforms undocumented
    ExcludePlatforms []ConditionalAccessDevicePlatform `json:"excludePlatforms,omitempty"`
    // IncludePlatforms undocumented
    IncludePlatforms []ConditionalAccessDevicePlatform `json:"includePlatforms,omitempty"`
}

// ConditionalAccessPolicy undocumented
type ConditionalAccessPolicy struct {
    // Entity is the base model of ConditionalAccessPolicy
    Entity
    // Conditions undocumented
    Conditions *ConditionalAccessConditionSet `json:"conditions,omitempty"`
    // CreatedDateTime undocumented
    CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
    // Description undocumented
    Description *string `json:"description,omitempty"`
    // DisplayName undocumented
    DisplayName *string `json:"displayName,omitempty"`
    // GrantControls undocumented
    GrantControls *ConditionalAccessGrantControls `json:"grantControls,omitempty"`
    // ModifiedDateTime undocumented
    ModifiedDateTime *time.Time `json:"modifiedDateTime,omitempty"`
    // SessionControls undocumented
    SessionControls *ConditionalAccessSessionControls `json:"sessionControls,omitempty"`
    // State undocumented
    State *ConditionalAccessPolicyState `json:"state,omitempty"`
}

// ConditionalAccessPolicyDetail undocumented
type ConditionalAccessPolicyDetail struct {
    // Object is the base model of ConditionalAccessPolicyDetail
    Object
    // Conditions undocumented
    Conditions *ConditionalAccessConditionSet `json:"conditions,omitempty"`
    // GrantControls undocumented
    GrantControls *ConditionalAccessGrantControls `json:"grantControls,omitempty"`
    // SessionControls undocumented
    SessionControls *ConditionalAccessSessionControls `json:"sessionControls,omitempty"`
}

// ConditionalAccessRoot undocumented
type ConditionalAccessRoot struct {
    // Entity is the base model of ConditionalAccessRoot
    Entity
    // AuthenticationStrength undocumented
    AuthenticationStrength *AuthenticationStrengthRoot `json:"authenticationStrength,omitempty"`
    // AuthenticationStrengths undocumented
    AuthenticationStrengths *AuthenticationStrengthRoot `json:"authenticationStrengths,omitempty"`
    // AuthenticationContextClassReferences undocumented
    AuthenticationContextClassReferences []AuthenticationContextClassReference `json:"authenticationContextClassReferences,omitempty"`
    // NamedLocations undocumented
    NamedLocations []NamedLocation `json:"namedLocations,omitempty"`
    // Policies undocumented
    Policies []ConditionalAccessPolicy `json:"policies,omitempty"`
    // Templates undocumented
    Templates []ConditionalAccessTemplate `json:"templates,omitempty"`
}

// ConditionalAccessRuleSatisfied undocumented
type ConditionalAccessRuleSatisfied struct {
    // Object is the base model of ConditionalAccessRuleSatisfied
    Object
    // ConditionalAccessCondition undocumented
    ConditionalAccessCondition *ConditionalAccessConditions `json:"conditionalAccessCondition,omitempty"`
    // RuleSatisfied undocumented
    RuleSatisfied *ConditionalAccessRule `json:"ruleSatisfied,omitempty"`
}

// ConditionalAccessSessionControl undocumented
type ConditionalAccessSessionControl struct {
    // Object is the base model of ConditionalAccessSessionControl
    Object
    // IsEnabled undocumented
    IsEnabled *bool `json:"isEnabled,omitempty"`
}

// ConditionalAccessSessionControls undocumented
type ConditionalAccessSessionControls struct {
    // Object is the base model of ConditionalAccessSessionControls
    Object
    // ApplicationEnforcedRestrictions undocumented
    ApplicationEnforcedRestrictions *ApplicationEnforcedRestrictionsSessionControl `json:"applicationEnforcedRestrictions,omitempty"`
    // CloudAppSecurity undocumented
    CloudAppSecurity *CloudAppSecuritySessionControl `json:"cloudAppSecurity,omitempty"`
    // ContinuousAccessEvaluation undocumented
    ContinuousAccessEvaluation *ContinuousAccessEvaluationSessionControl `json:"continuousAccessEvaluation,omitempty"`
    // DisableResilienceDefaults undocumented
    DisableResilienceDefaults *bool `json:"disableResilienceDefaults,omitempty"`
    // PersistentBrowser undocumented
    PersistentBrowser *PersistentBrowserSessionControl `json:"persistentBrowser,omitempty"`
    // SecureSignInSession undocumented
    SecureSignInSession *SecureSignInSessionControl `json:"secureSignInSession,omitempty"`
    // SignInFrequency undocumented
    SignInFrequency *SignInFrequencySessionControl `json:"signInFrequency,omitempty"`
}

// ConditionalAccessTemplate undocumented
type ConditionalAccessTemplate struct {
    // Entity is the base model of ConditionalAccessTemplate
    Entity
    // Description undocumented
    Description *string `json:"description,omitempty"`
    // Details undocumented
    Details *ConditionalAccessPolicyDetail `json:"details,omitempty"`
    // Name undocumented
    Name *string `json:"name,omitempty"`
    // Scenarios undocumented
    Scenarios *TemplateScenarios `json:"scenarios,omitempty"`
}

// ConditionalAccessUsers undocumented
type ConditionalAccessUsers struct {
    // Object is the base model of ConditionalAccessUsers
    Object
    // ExcludeGroups undocumented
    ExcludeGroups []string `json:"excludeGroups,omitempty"`
    // ExcludeGuestsOrExternalUsers undocumented
    ExcludeGuestsOrExternalUsers *ConditionalAccessGuestsOrExternalUsers `json:"excludeGuestsOrExternalUsers,omitempty"`
    // ExcludeRoles undocumented
    ExcludeRoles []string `json:"excludeRoles,omitempty"`
    // ExcludeUsers undocumented
    ExcludeUsers []string `json:"excludeUsers,omitempty"`
    // IncludeGroups undocumented
    IncludeGroups []string `json:"includeGroups,omitempty"`
    // IncludeGuestsOrExternalUsers undocumented
    IncludeGuestsOrExternalUsers *ConditionalAccessGuestsOrExternalUsers `json:"includeGuestsOrExternalUsers,omitempty"`
    // IncludeRoles undocumented
    IncludeRoles []string `json:"includeRoles,omitempty"`
    // IncludeUsers undocumented
    IncludeUsers []string `json:"includeUsers,omitempty"`
}
