
// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph


// IntegerRange undocumented
type IntegerRange struct {
    // Object is the base model of IntegerRange
    Object
    // End undocumented
    End *int `json:"end,omitempty"`
    // Maximum undocumented
    Maximum *int `json:"maximum,omitempty"`
    // Minimum undocumented
    Minimum *int `json:"minimum,omitempty"`
    // Start undocumented
    Start *int `json:"start,omitempty"`
}
