// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// ServiceAnnouncement undocumented
type ServiceAnnouncement struct {
	// Entity is the base model of ServiceAnnouncement
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// HealthOverviews undocumented
	HealthOverviews []ServiceHealth `json:"healthOverviews,omitempty"`
	// Issues undocumented
	Issues []ServiceHealthIssue `json:"issues,omitempty"`
	// Messages undocumented
	Messages []ServiceUpdateMessage `json:"messages,omitempty"`
}

func NewServiceAnnouncement() (*ServiceAnnouncement, error) {
	newServiceAnnouncement := &ServiceAnnouncement{
		ODataType: "#microsoft.graph.ServiceAnnouncement",
	}
	return newServiceAnnouncement, nil
}

// ServiceAnnouncementAttachment undocumented
type ServiceAnnouncementAttachment struct {
	// Entity is the base model of ServiceAnnouncementAttachment
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// Content undocumented
	Content *Stream `json:"content,omitempty"`
	// ContentType undocumented
	ContentType *string `json:"contentType,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// Name undocumented
	Name *string `json:"name,omitempty"`
	// Size undocumented
	Size *int `json:"size,omitempty"`
}

func NewServiceAnnouncementAttachment() (*ServiceAnnouncementAttachment, error) {
	newServiceAnnouncementAttachment := &ServiceAnnouncementAttachment{
		ODataType: "#microsoft.graph.ServiceAnnouncementAttachment",
	}
	return newServiceAnnouncementAttachment, nil
}

// ServiceAnnouncementBase undocumented
type ServiceAnnouncementBase struct {
	// Entity is the base model of ServiceAnnouncementBase
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// Details undocumented
	Details []KeyValuePair `json:"details,omitempty"`
	// EndDateTime undocumented
	EndDateTime *time.Time `json:"endDateTime,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// StartDateTime undocumented
	StartDateTime *time.Time `json:"startDateTime,omitempty"`
	// Title undocumented
	Title *string `json:"title,omitempty"`
}

func NewServiceAnnouncementBase() (*ServiceAnnouncementBase, error) {
	newServiceAnnouncementBase := &ServiceAnnouncementBase{
		ODataType: "#microsoft.graph.ServiceAnnouncementBase",
	}
	return newServiceAnnouncementBase, nil
}

// ServiceHealth undocumented
type ServiceHealth struct {
	// Entity is the base model of ServiceHealth
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// Service undocumented
	Service *string `json:"service,omitempty"`
	// Status undocumented
	Status *ServiceHealthStatus `json:"status,omitempty"`
	// Issues undocumented
	Issues []ServiceHealthIssue `json:"issues,omitempty"`
}

func NewServiceHealth() (*ServiceHealth, error) {
	newServiceHealth := &ServiceHealth{
		ODataType: "#microsoft.graph.ServiceHealth",
	}
	return newServiceHealth, nil
}

// ServiceHealthIssue undocumented
type ServiceHealthIssue struct {
	// ServiceAnnouncementBase is the base model of ServiceHealthIssue
	ServiceAnnouncementBase

	ODataType string `json:"@odata.type,omitempty"`
	// Classification undocumented
	Classification *ServiceHealthClassificationType `json:"classification,omitempty"`
	// Feature undocumented
	Feature *string `json:"feature,omitempty"`
	// FeatureGroup undocumented
	FeatureGroup *string `json:"featureGroup,omitempty"`
	// ImpactDescription undocumented
	ImpactDescription *string `json:"impactDescription,omitempty"`
	// IsResolved undocumented
	IsResolved *bool `json:"isResolved,omitempty"`
	// Origin undocumented
	Origin *ServiceHealthOrigin `json:"origin,omitempty"`
	// Posts undocumented
	Posts []ServiceHealthIssuePost `json:"posts,omitempty"`
	// Service undocumented
	Service *string `json:"service,omitempty"`
	// Status undocumented
	Status *ServiceHealthStatus `json:"status,omitempty"`
}

func NewServiceHealthIssue() (*ServiceHealthIssue, error) {
	newServiceHealthIssue := &ServiceHealthIssue{
		ODataType: "#microsoft.graph.ServiceHealthIssue",
	}
	return newServiceHealthIssue, nil
}

// ServiceHealthIssuePost undocumented
type ServiceHealthIssuePost struct {
	// Object is the base model of ServiceHealthIssuePost
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// Description undocumented
	Description *ItemBody `json:"description,omitempty"`
	// PostType undocumented
	PostType *PostType `json:"postType,omitempty"`
}

func NewServiceHealthIssuePost() (*ServiceHealthIssuePost, error) {
	newServiceHealthIssuePost := &ServiceHealthIssuePost{
		ODataType: "#microsoft.graph.ServiceHealthIssuePost",
	}
	return newServiceHealthIssuePost, nil
}

// ServiceHostedMediaConfig undocumented
type ServiceHostedMediaConfig struct {
	// MediaConfig is the base model of ServiceHostedMediaConfig
	MediaConfig

	ODataType string `json:"@odata.type,omitempty"`
	// PreFetchMedia undocumented
	PreFetchMedia []MediaInfo `json:"preFetchMedia,omitempty"`
}

func NewServiceHostedMediaConfig() (*ServiceHostedMediaConfig, error) {
	newServiceHostedMediaConfig := &ServiceHostedMediaConfig{
		ODataType: "#microsoft.graph.ServiceHostedMediaConfig",
	}
	return newServiceHostedMediaConfig, nil
}

// ServiceInformation undocumented
type ServiceInformation struct {
	// Object is the base model of ServiceInformation
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// Name undocumented
	Name *string `json:"name,omitempty"`
	// WebURL undocumented
	WebURL *string `json:"webUrl,omitempty"`
}

func NewServiceInformation() (*ServiceInformation, error) {
	newServiceInformation := &ServiceInformation{
		ODataType: "#microsoft.graph.ServiceInformation",
	}
	return newServiceInformation, nil
}

// ServiceNowAuthenticationMethod undocumented
type ServiceNowAuthenticationMethod struct {
	// Object is the base model of ServiceNowAuthenticationMethod
	Object

	ODataType string `json:"@odata.type,omitempty"`
}

func NewServiceNowAuthenticationMethod() (*ServiceNowAuthenticationMethod, error) {
	newServiceNowAuthenticationMethod := &ServiceNowAuthenticationMethod{
		ODataType: "#microsoft.graph.ServiceNowAuthenticationMethod",
	}
	return newServiceNowAuthenticationMethod, nil
}

// ServiceNowConnection undocumented
type ServiceNowConnection struct {
	// Entity is the base model of ServiceNowConnection
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// AuthenticationMethod undocumented
	AuthenticationMethod *ServiceNowAuthenticationMethod `json:"authenticationMethod,omitempty"`
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// IncidentAPIURL undocumented
	IncidentAPIURL *string `json:"incidentApiUrl,omitempty"`
	// InstanceURL undocumented
	InstanceURL *string `json:"instanceUrl,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// LastQueriedDateTime undocumented
	LastQueriedDateTime *time.Time `json:"lastQueriedDateTime,omitempty"`
	// ServiceNowConnectionStatus undocumented
	ServiceNowConnectionStatus *ServiceNowConnectionStatus `json:"serviceNowConnectionStatus,omitempty"`
}

func NewServiceNowConnection() (*ServiceNowConnection, error) {
	newServiceNowConnection := &ServiceNowConnection{
		ODataType: "#microsoft.graph.ServiceNowConnection",
	}
	return newServiceNowConnection, nil
}

// ServiceNowOAuthSecretAuthentication undocumented
type ServiceNowOAuthSecretAuthentication struct {
	// ServiceNowAuthenticationMethod is the base model of ServiceNowOAuthSecretAuthentication
	ServiceNowAuthenticationMethod

	ODataType string `json:"@odata.type,omitempty"`
	// AppID undocumented
	AppID *string `json:"appId,omitempty"`
}

func NewServiceNowOAuthSecretAuthentication() (*ServiceNowOAuthSecretAuthentication, error) {
	newServiceNowOAuthSecretAuthentication := &ServiceNowOAuthSecretAuthentication{
		ODataType: "#microsoft.graph.ServiceNowOauthSecretAuthentication",
	}
	return newServiceNowOAuthSecretAuthentication, nil
}

// ServicePlanInfo undocumented
type ServicePlanInfo struct {
	// Object is the base model of ServicePlanInfo
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// AppliesTo undocumented
	AppliesTo *string `json:"appliesTo,omitempty"`
	// ProvisioningStatus undocumented
	ProvisioningStatus *string `json:"provisioningStatus,omitempty"`
	// ServicePlanID undocumented
	ServicePlanID *UUID `json:"servicePlanId,omitempty"`
	// ServicePlanName undocumented
	ServicePlanName *string `json:"servicePlanName,omitempty"`
}

func NewServicePlanInfo() (*ServicePlanInfo, error) {
	newServicePlanInfo := &ServicePlanInfo{
		ODataType: "#microsoft.graph.ServicePlanInfo",
	}
	return newServicePlanInfo, nil
}

// ServicePrincipal undocumented
type ServicePrincipal struct {
	// DirectoryObject is the base model of ServicePrincipal
	DirectoryObject

	ODataType string `json:"@odata.type,omitempty"`
	// PasswordSingleSignOnSettings undocumented
	PasswordSingleSignOnSettings *PasswordSingleSignOnSettings `json:"passwordSingleSignOnSettings,omitempty"`
	// AccountEnabled undocumented
	AccountEnabled *bool `json:"accountEnabled,omitempty"`
	// AddIns undocumented
	AddIns []AddIn `json:"addIns,omitempty"`
	// AlternativeNames undocumented
	AlternativeNames []string `json:"alternativeNames,omitempty"`
	// AppDescription undocumented
	AppDescription *string `json:"appDescription,omitempty"`
	// AppDisplayName undocumented
	AppDisplayName *string `json:"appDisplayName,omitempty"`
	// AppID undocumented
	AppID *string `json:"appId,omitempty"`
	// ApplicationTemplateID undocumented
	ApplicationTemplateID *string `json:"applicationTemplateId,omitempty"`
	// AppOwnerOrganizationID undocumented
	AppOwnerOrganizationID *UUID `json:"appOwnerOrganizationId,omitempty"`
	// AppRoleAssignmentRequired undocumented
	AppRoleAssignmentRequired *bool `json:"appRoleAssignmentRequired,omitempty"`
	// AppRoles undocumented
	AppRoles []AppRole `json:"appRoles,omitempty"`
	// CustomSecurityAttributes undocumented
	CustomSecurityAttributes *CustomSecurityAttributeValue `json:"customSecurityAttributes,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisabledByMicrosoftStatus undocumented
	DisabledByMicrosoftStatus *string `json:"disabledByMicrosoftStatus,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// ErrorURL undocumented
	ErrorURL *string `json:"errorUrl,omitempty"`
	// Homepage undocumented
	Homepage *string `json:"homepage,omitempty"`
	// Info undocumented
	Info *InformationalURL `json:"info,omitempty"`
	// KeyCredentials undocumented
	KeyCredentials []KeyCredential `json:"keyCredentials,omitempty"`
	// LoginURL undocumented
	LoginURL *string `json:"loginUrl,omitempty"`
	// LogoutURL undocumented
	LogoutURL *string `json:"logoutUrl,omitempty"`
	// Notes undocumented
	Notes *string `json:"notes,omitempty"`
	// NotificationEmailAddresses undocumented
	NotificationEmailAddresses []string `json:"notificationEmailAddresses,omitempty"`
	// PasswordCredentials undocumented
	PasswordCredentials []PasswordCredential `json:"passwordCredentials,omitempty"`
	// PreferredSingleSignOnMode undocumented
	PreferredSingleSignOnMode *string `json:"preferredSingleSignOnMode,omitempty"`
	// PreferredTokenSigningKeyEndDateTime undocumented
	PreferredTokenSigningKeyEndDateTime *time.Time `json:"preferredTokenSigningKeyEndDateTime,omitempty"`
	// PreferredTokenSigningKeyThumbprint undocumented
	PreferredTokenSigningKeyThumbprint *string `json:"preferredTokenSigningKeyThumbprint,omitempty"`
	// PublishedPermissionScopes undocumented
	PublishedPermissionScopes []PermissionScope `json:"publishedPermissionScopes,omitempty"`
	// PublisherName undocumented
	PublisherName *string `json:"publisherName,omitempty"`
	// ReplyUrls undocumented
	ReplyUrls []string `json:"replyUrls,omitempty"`
	// SamlMetadataURL undocumented
	SamlMetadataURL *string `json:"samlMetadataUrl,omitempty"`
	// SamlSingleSignOnSettings undocumented
	SamlSingleSignOnSettings *SamlSingleSignOnSettings `json:"samlSingleSignOnSettings,omitempty"`
	// ServicePrincipalNames undocumented
	ServicePrincipalNames []string `json:"servicePrincipalNames,omitempty"`
	// ServicePrincipalType undocumented
	ServicePrincipalType *string `json:"servicePrincipalType,omitempty"`
	// SignInAudience undocumented
	SignInAudience *string `json:"signInAudience,omitempty"`
	// Tags undocumented
	Tags []string `json:"tags,omitempty"`
	// TokenEncryptionKeyID undocumented
	TokenEncryptionKeyID *UUID `json:"tokenEncryptionKeyId,omitempty"`
	// VerifiedPublisher undocumented
	VerifiedPublisher *VerifiedPublisher `json:"verifiedPublisher,omitempty"`
	// AppManagementPolicies undocumented
	AppManagementPolicies []AppManagementPolicy `json:"appManagementPolicies,omitempty"`
	// AppRoleAssignedTo undocumented
	AppRoleAssignedTo []AppRoleAssignment `json:"appRoleAssignedTo,omitempty"`
	// AppRoleAssignments undocumented
	AppRoleAssignments []AppRoleAssignment `json:"appRoleAssignments,omitempty"`
	// ClaimsMappingPolicies undocumented
	ClaimsMappingPolicies []ClaimsMappingPolicy `json:"claimsMappingPolicies,omitempty"`
	// CreatedObjects undocumented
	CreatedObjects []DirectoryObject `json:"createdObjects,omitempty"`
	// DelegatedPermissionClassifications undocumented
	DelegatedPermissionClassifications []DelegatedPermissionClassification `json:"delegatedPermissionClassifications,omitempty"`
	// Endpoints undocumented
	Endpoints []Endpoint `json:"endpoints,omitempty"`
	// FederatedIdentityCredentials undocumented
	FederatedIdentityCredentials []FederatedIdentityCredential `json:"federatedIdentityCredentials,omitempty"`
	// HomeRealmDiscoveryPolicies undocumented
	HomeRealmDiscoveryPolicies []HomeRealmDiscoveryPolicy `json:"homeRealmDiscoveryPolicies,omitempty"`
	// LicenseDetails undocumented
	LicenseDetails []LicenseDetails `json:"licenseDetails,omitempty"`
	// MemberOf undocumented
	MemberOf []DirectoryObject `json:"memberOf,omitempty"`
	// OAuth2PermissionGrants undocumented
	OAuth2PermissionGrants []OAuth2PermissionGrant `json:"oauth2PermissionGrants,omitempty"`
	// OwnedObjects undocumented
	OwnedObjects []DirectoryObject `json:"ownedObjects,omitempty"`
	// Owners undocumented
	Owners []DirectoryObject `json:"owners,omitempty"`
	// TokenIssuancePolicies undocumented
	TokenIssuancePolicies []TokenIssuancePolicy `json:"tokenIssuancePolicies,omitempty"`
	// TokenLifetimePolicies undocumented
	TokenLifetimePolicies []TokenLifetimePolicy `json:"tokenLifetimePolicies,omitempty"`
	// TransitiveMemberOf undocumented
	TransitiveMemberOf []DirectoryObject `json:"transitiveMemberOf,omitempty"`
	// Synchronization undocumented
	Synchronization *Synchronization `json:"synchronization,omitempty"`
}

func NewServicePrincipal() (*ServicePrincipal, error) {
	newServicePrincipal := &ServicePrincipal{
		ODataType: "#microsoft.graph.ServicePrincipal",
	}
	return newServicePrincipal, nil
}

// ServicePrincipalCreationConditionSet undocumented
type ServicePrincipalCreationConditionSet struct {
	// Entity is the base model of ServicePrincipalCreationConditionSet
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// ApplicationIDs undocumented
	ApplicationIDs []string `json:"applicationIds,omitempty"`
	// ApplicationPublisherIDs undocumented
	ApplicationPublisherIDs []string `json:"applicationPublisherIds,omitempty"`
	// ApplicationsFromVerifiedPublisherOnly undocumented
	ApplicationsFromVerifiedPublisherOnly *bool `json:"applicationsFromVerifiedPublisherOnly,omitempty"`
	// ApplicationTenantIDs undocumented
	ApplicationTenantIDs []string `json:"applicationTenantIds,omitempty"`
	// CertifiedApplicationsOnly undocumented
	CertifiedApplicationsOnly *bool `json:"certifiedApplicationsOnly,omitempty"`
}

func NewServicePrincipalCreationConditionSet() (*ServicePrincipalCreationConditionSet, error) {
	newServicePrincipalCreationConditionSet := &ServicePrincipalCreationConditionSet{
		ODataType: "#microsoft.graph.ServicePrincipalCreationConditionSet",
	}
	return newServicePrincipalCreationConditionSet, nil
}

// ServicePrincipalCreationPolicy undocumented
type ServicePrincipalCreationPolicy struct {
	// PolicyBase is the base model of ServicePrincipalCreationPolicy
	PolicyBase

	ODataType string `json:"@odata.type,omitempty"`
	// IsBuiltIn undocumented
	IsBuiltIn *bool `json:"isBuiltIn,omitempty"`
	// Excludes undocumented
	Excludes []ServicePrincipalCreationConditionSet `json:"excludes,omitempty"`
	// Includes undocumented
	Includes []ServicePrincipalCreationConditionSet `json:"includes,omitempty"`
}

func NewServicePrincipalCreationPolicy() (*ServicePrincipalCreationPolicy, error) {
	newServicePrincipalCreationPolicy := &ServicePrincipalCreationPolicy{
		ODataType: "#microsoft.graph.ServicePrincipalCreationPolicy",
	}
	return newServicePrincipalCreationPolicy, nil
}

// ServicePrincipalIdentity undocumented
type ServicePrincipalIdentity struct {
	// Identity is the base model of ServicePrincipalIdentity
	Identity

	ODataType string `json:"@odata.type,omitempty"`
	// AppID undocumented
	AppID *string `json:"appId,omitempty"`
}

func NewServicePrincipalIdentity() (*ServicePrincipalIdentity, error) {
	newServicePrincipalIdentity := &ServicePrincipalIdentity{
		ODataType: "#microsoft.graph.ServicePrincipalIdentity",
	}
	return newServicePrincipalIdentity, nil
}

// ServicePrincipalLockConfiguration undocumented
type ServicePrincipalLockConfiguration struct {
	// Object is the base model of ServicePrincipalLockConfiguration
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// AllProperties undocumented
	AllProperties *bool `json:"allProperties,omitempty"`
	// CredentialsWithUsageSign undocumented
	CredentialsWithUsageSign *bool `json:"credentialsWithUsageSign,omitempty"`
	// CredentialsWithUsageVerify undocumented
	CredentialsWithUsageVerify *bool `json:"credentialsWithUsageVerify,omitempty"`
	// IsEnabled undocumented
	IsEnabled *bool `json:"isEnabled,omitempty"`
	// TokenEncryptionKeyID undocumented
	TokenEncryptionKeyID *bool `json:"tokenEncryptionKeyId,omitempty"`
}

func NewServicePrincipalLockConfiguration() (*ServicePrincipalLockConfiguration, error) {
	newServicePrincipalLockConfiguration := &ServicePrincipalLockConfiguration{
		ODataType: "#microsoft.graph.ServicePrincipalLockConfiguration",
	}
	return newServicePrincipalLockConfiguration, nil
}

// ServicePrincipalRiskDetection undocumented
type ServicePrincipalRiskDetection struct {
	// Entity is the base model of ServicePrincipalRiskDetection
	Entity

	ODataType string `json:"@odata.type,omitempty"`
	// Activity undocumented
	Activity *ActivityType `json:"activity,omitempty"`
	// ActivityDateTime undocumented
	ActivityDateTime *time.Time `json:"activityDateTime,omitempty"`
	// AdditionalInfo undocumented
	AdditionalInfo *string `json:"additionalInfo,omitempty"`
	// AppID undocumented
	AppID *string `json:"appId,omitempty"`
	// CorrelationID undocumented
	CorrelationID *string `json:"correlationId,omitempty"`
	// DetectedDateTime undocumented
	DetectedDateTime *time.Time `json:"detectedDateTime,omitempty"`
	// DetectionTimingType undocumented
	DetectionTimingType *RiskDetectionTimingType `json:"detectionTimingType,omitempty"`
	// IPAddress undocumented
	IPAddress *string `json:"ipAddress,omitempty"`
	// KeyIDs undocumented
	KeyIDs []string `json:"keyIds,omitempty"`
	// LastUpdatedDateTime undocumented
	LastUpdatedDateTime *time.Time `json:"lastUpdatedDateTime,omitempty"`
	// Location undocumented
	Location *SignInLocation `json:"location,omitempty"`
	// RequestID undocumented
	RequestID *string `json:"requestId,omitempty"`
	// RiskDetail undocumented
	RiskDetail *RiskDetail `json:"riskDetail,omitempty"`
	// RiskEventType undocumented
	RiskEventType *string `json:"riskEventType,omitempty"`
	// RiskLevel undocumented
	RiskLevel *RiskLevel `json:"riskLevel,omitempty"`
	// RiskState undocumented
	RiskState *RiskState `json:"riskState,omitempty"`
	// ServicePrincipalDisplayName undocumented
	ServicePrincipalDisplayName *string `json:"servicePrincipalDisplayName,omitempty"`
	// ServicePrincipalID undocumented
	ServicePrincipalID *string `json:"servicePrincipalId,omitempty"`
	// Source undocumented
	Source *string `json:"source,omitempty"`
	// TokenIssuerType undocumented
	TokenIssuerType *TokenIssuerType `json:"tokenIssuerType,omitempty"`
}

func NewServicePrincipalRiskDetection() (*ServicePrincipalRiskDetection, error) {
	newServicePrincipalRiskDetection := &ServicePrincipalRiskDetection{
		ODataType: "#microsoft.graph.ServicePrincipalRiskDetection",
	}
	return newServicePrincipalRiskDetection, nil
}

// ServiceProvisioningError undocumented
type ServiceProvisioningError struct {
	// Object is the base model of ServiceProvisioningError
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// IsResolved undocumented
	IsResolved *bool `json:"isResolved,omitempty"`
	// ServiceInstance undocumented
	ServiceInstance *string `json:"serviceInstance,omitempty"`
}

func NewServiceProvisioningError() (*ServiceProvisioningError, error) {
	newServiceProvisioningError := &ServiceProvisioningError{
		ODataType: "#microsoft.graph.ServiceProvisioningError",
	}
	return newServiceProvisioningError, nil
}

// ServiceProvisioningLinkedResourceErrorDetail undocumented
type ServiceProvisioningLinkedResourceErrorDetail struct {
	// ServiceProvisioningResourceErrorDetail is the base model of ServiceProvisioningLinkedResourceErrorDetail
	ServiceProvisioningResourceErrorDetail

	ODataType string `json:"@odata.type,omitempty"`
	// PropertyName undocumented
	PropertyName *string `json:"propertyName,omitempty"`
	// Target undocumented
	Target *string `json:"target,omitempty"`
}

func NewServiceProvisioningLinkedResourceErrorDetail() (*ServiceProvisioningLinkedResourceErrorDetail, error) {
	newServiceProvisioningLinkedResourceErrorDetail := &ServiceProvisioningLinkedResourceErrorDetail{
		ODataType: "#microsoft.graph.ServiceProvisioningLinkedResourceErrorDetail",
	}
	return newServiceProvisioningLinkedResourceErrorDetail, nil
}

// ServiceProvisioningResourceError undocumented
type ServiceProvisioningResourceError struct {
	// ServiceProvisioningError is the base model of ServiceProvisioningResourceError
	ServiceProvisioningError

	ODataType string `json:"@odata.type,omitempty"`
	// Errors undocumented
	Errors []ServiceProvisioningResourceErrorDetail `json:"errors,omitempty"`
}

func NewServiceProvisioningResourceError() (*ServiceProvisioningResourceError, error) {
	newServiceProvisioningResourceError := &ServiceProvisioningResourceError{
		ODataType: "#microsoft.graph.ServiceProvisioningResourceError",
	}
	return newServiceProvisioningResourceError, nil
}

// ServiceProvisioningResourceErrorDetail undocumented
type ServiceProvisioningResourceErrorDetail struct {
	// Object is the base model of ServiceProvisioningResourceErrorDetail
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// Code undocumented
	Code *string `json:"code,omitempty"`
	// Details undocumented
	Details *string `json:"details,omitempty"`
	// Message undocumented
	Message *string `json:"message,omitempty"`
}

func NewServiceProvisioningResourceErrorDetail() (*ServiceProvisioningResourceErrorDetail, error) {
	newServiceProvisioningResourceErrorDetail := &ServiceProvisioningResourceErrorDetail{
		ODataType: "#microsoft.graph.ServiceProvisioningResourceErrorDetail",
	}
	return newServiceProvisioningResourceErrorDetail, nil
}

// ServiceProvisioningXMLError undocumented
type ServiceProvisioningXMLError struct {
	// ServiceProvisioningError is the base model of ServiceProvisioningXMLError
	ServiceProvisioningError

	ODataType string `json:"@odata.type,omitempty"`
	// ErrorDetail undocumented
	ErrorDetail *string `json:"errorDetail,omitempty"`
}

func NewServiceProvisioningXMLError() (*ServiceProvisioningXMLError, error) {
	newServiceProvisioningXMLError := &ServiceProvisioningXMLError{
		ODataType: "#microsoft.graph.ServiceProvisioningXmlError",
	}
	return newServiceProvisioningXMLError, nil
}

// ServiceUpdateMessage undocumented
type ServiceUpdateMessage struct {
	// ServiceAnnouncementBase is the base model of ServiceUpdateMessage
	ServiceAnnouncementBase

	ODataType string `json:"@odata.type,omitempty"`
	// ActionRequiredByDateTime undocumented
	ActionRequiredByDateTime *time.Time `json:"actionRequiredByDateTime,omitempty"`
	// AttachmentsArchive undocumented
	AttachmentsArchive *Stream `json:"attachmentsArchive,omitempty"`
	// Body undocumented
	Body *ItemBody `json:"body,omitempty"`
	// Category undocumented
	Category *ServiceUpdateCategory `json:"category,omitempty"`
	// HasAttachments undocumented
	HasAttachments *bool `json:"hasAttachments,omitempty"`
	// IsMajorChange undocumented
	IsMajorChange *bool `json:"isMajorChange,omitempty"`
	// Services undocumented
	Services []string `json:"services,omitempty"`
	// Severity undocumented
	Severity *ServiceUpdateSeverity `json:"severity,omitempty"`
	// Tags undocumented
	Tags []string `json:"tags,omitempty"`
	// ViewPoint undocumented
	ViewPoint *ServiceUpdateMessageViewpoint `json:"viewPoint,omitempty"`
	// Attachments undocumented
	Attachments []ServiceAnnouncementAttachment `json:"attachments,omitempty"`
}

func NewServiceUpdateMessage() (*ServiceUpdateMessage, error) {
	newServiceUpdateMessage := &ServiceUpdateMessage{
		ODataType: "#microsoft.graph.ServiceUpdateMessage",
	}
	return newServiceUpdateMessage, nil
}

// ServiceUpdateMessageViewpoint undocumented
type ServiceUpdateMessageViewpoint struct {
	// Object is the base model of ServiceUpdateMessageViewpoint
	Object

	ODataType string `json:"@odata.type,omitempty"`
	// IsArchived undocumented
	IsArchived *bool `json:"isArchived,omitempty"`
	// IsFavorited undocumented
	IsFavorited *bool `json:"isFavorited,omitempty"`
	// IsRead undocumented
	IsRead *bool `json:"isRead,omitempty"`
}

func NewServiceUpdateMessageViewpoint() (*ServiceUpdateMessageViewpoint, error) {
	newServiceUpdateMessageViewpoint := &ServiceUpdateMessageViewpoint{
		ODataType: "#microsoft.graph.ServiceUpdateMessageViewpoint",
	}
	return newServiceUpdateMessageViewpoint, nil
}
