
// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph


// InformationProtection undocumented
type InformationProtection struct {
    // Entity is the base model of InformationProtection
    Entity
    // Bitlocker undocumented
    Bitlocker *Bitlocker `json:"bitlocker,omitempty"`
    // DataLossPreventionPolicies undocumented
    DataLossPreventionPolicies []DataLossPreventionPolicy `json:"dataLossPreventionPolicies,omitempty"`
    // SensitivityLabels undocumented
    SensitivityLabels []SensitivityLabel `json:"sensitivityLabels,omitempty"`
    // SensitivityPolicySettings undocumented
    SensitivityPolicySettings *SensitivityPolicySettings `json:"sensitivityPolicySettings,omitempty"`
    // Policy undocumented
    Policy *InformationProtectionPolicy `json:"policy,omitempty"`
    // ThreatAssessmentRequests undocumented
    ThreatAssessmentRequests []ThreatAssessmentRequest `json:"threatAssessmentRequests,omitempty"`
}

// InformationProtectionAction undocumented
type InformationProtectionAction struct {
    // Object is the base model of InformationProtectionAction
    Object
}

// InformationProtectionContentLabel undocumented
type InformationProtectionContentLabel struct {
    // Object is the base model of InformationProtectionContentLabel
    Object
    // AssignmentMethod undocumented
    AssignmentMethod *AssignmentMethod `json:"assignmentMethod,omitempty"`
    // CreationDateTime undocumented
    CreationDateTime *time.Time `json:"creationDateTime,omitempty"`
    // Label undocumented
    Label *LabelDetails `json:"label,omitempty"`
}

// InformationProtectionLabel undocumented
type InformationProtectionLabel struct {
    // Entity is the base model of InformationProtectionLabel
    Entity
    // Color undocumented
    Color *string `json:"color,omitempty"`
    // Description undocumented
    Description *string `json:"description,omitempty"`
    // IsActive undocumented
    IsActive *bool `json:"isActive,omitempty"`
    // Name undocumented
    Name *string `json:"name,omitempty"`
    // Parent undocumented
    Parent *ParentLabelDetails `json:"parent,omitempty"`
    // Sensitivity undocumented
    Sensitivity *int `json:"sensitivity,omitempty"`
    // Tooltip undocumented
    Tooltip *string `json:"tooltip,omitempty"`
}

// InformationProtectionPolicy undocumented
type InformationProtectionPolicy struct {
    // Entity is the base model of InformationProtectionPolicy
    Entity
    // Labels undocumented
    Labels []InformationProtectionLabel `json:"labels,omitempty"`
}
