// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// JustifyActionRequestBuilder is request builder for JustifyAction
type JustifyActionRequestBuilder struct{ BaseRequestBuilder }

// Request returns JustifyActionRequest
func (b *JustifyActionRequestBuilder) Request() *JustifyActionRequest {
	return &JustifyActionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// JustifyActionRequest is request for JustifyAction
type JustifyActionRequest struct{ BaseRequest }

// Get performs GET request for JustifyAction
func (r *JustifyActionRequest) Get(ctx context.Context) (resObj *JustifyAction, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for JustifyAction
func (r *JustifyActionRequest) Update(ctx context.Context, reqObj *JustifyAction) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for JustifyAction
func (r *JustifyActionRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
