// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// Win32LobAppRequestBuilder is request builder for Win32LobApp
type Win32LobAppRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppRequest
func (b *Win32LobAppRequestBuilder) Request() *Win32LobAppRequest {
	return &Win32LobAppRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppRequest is request for Win32LobApp
type Win32LobAppRequest struct{ BaseRequest }

// Get performs GET request for Win32LobApp
func (r *Win32LobAppRequest) Get(ctx context.Context) (resObj *Win32LobApp, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobApp
func (r *Win32LobAppRequest) Update(ctx context.Context, reqObj *Win32LobApp) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobApp
func (r *Win32LobAppRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppAssignmentSettingsRequestBuilder is request builder for Win32LobAppAssignmentSettings
type Win32LobAppAssignmentSettingsRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppAssignmentSettingsRequest
func (b *Win32LobAppAssignmentSettingsRequestBuilder) Request() *Win32LobAppAssignmentSettingsRequest {
	return &Win32LobAppAssignmentSettingsRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppAssignmentSettingsRequest is request for Win32LobAppAssignmentSettings
type Win32LobAppAssignmentSettingsRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppAssignmentSettings
func (r *Win32LobAppAssignmentSettingsRequest) Get(ctx context.Context) (resObj *Win32LobAppAssignmentSettings, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppAssignmentSettings
func (r *Win32LobAppAssignmentSettingsRequest) Update(ctx context.Context, reqObj *Win32LobAppAssignmentSettings) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppAssignmentSettings
func (r *Win32LobAppAssignmentSettingsRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppDetectionRequestBuilder is request builder for Win32LobAppDetection
type Win32LobAppDetectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppDetectionRequest
func (b *Win32LobAppDetectionRequestBuilder) Request() *Win32LobAppDetectionRequest {
	return &Win32LobAppDetectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppDetectionRequest is request for Win32LobAppDetection
type Win32LobAppDetectionRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppDetection
func (r *Win32LobAppDetectionRequest) Get(ctx context.Context) (resObj *Win32LobAppDetection, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppDetection
func (r *Win32LobAppDetectionRequest) Update(ctx context.Context, reqObj *Win32LobAppDetection) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppDetection
func (r *Win32LobAppDetectionRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppFileSystemDetectionRequestBuilder is request builder for Win32LobAppFileSystemDetection
type Win32LobAppFileSystemDetectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppFileSystemDetectionRequest
func (b *Win32LobAppFileSystemDetectionRequestBuilder) Request() *Win32LobAppFileSystemDetectionRequest {
	return &Win32LobAppFileSystemDetectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppFileSystemDetectionRequest is request for Win32LobAppFileSystemDetection
type Win32LobAppFileSystemDetectionRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppFileSystemDetection
func (r *Win32LobAppFileSystemDetectionRequest) Get(ctx context.Context) (resObj *Win32LobAppFileSystemDetection, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppFileSystemDetection
func (r *Win32LobAppFileSystemDetectionRequest) Update(ctx context.Context, reqObj *Win32LobAppFileSystemDetection) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppFileSystemDetection
func (r *Win32LobAppFileSystemDetectionRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppFileSystemRequirementRequestBuilder is request builder for Win32LobAppFileSystemRequirement
type Win32LobAppFileSystemRequirementRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppFileSystemRequirementRequest
func (b *Win32LobAppFileSystemRequirementRequestBuilder) Request() *Win32LobAppFileSystemRequirementRequest {
	return &Win32LobAppFileSystemRequirementRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppFileSystemRequirementRequest is request for Win32LobAppFileSystemRequirement
type Win32LobAppFileSystemRequirementRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppFileSystemRequirement
func (r *Win32LobAppFileSystemRequirementRequest) Get(ctx context.Context) (resObj *Win32LobAppFileSystemRequirement, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppFileSystemRequirement
func (r *Win32LobAppFileSystemRequirementRequest) Update(ctx context.Context, reqObj *Win32LobAppFileSystemRequirement) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppFileSystemRequirement
func (r *Win32LobAppFileSystemRequirementRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppFileSystemRuleRequestBuilder is request builder for Win32LobAppFileSystemRule
type Win32LobAppFileSystemRuleRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppFileSystemRuleRequest
func (b *Win32LobAppFileSystemRuleRequestBuilder) Request() *Win32LobAppFileSystemRuleRequest {
	return &Win32LobAppFileSystemRuleRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppFileSystemRuleRequest is request for Win32LobAppFileSystemRule
type Win32LobAppFileSystemRuleRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppFileSystemRule
func (r *Win32LobAppFileSystemRuleRequest) Get(ctx context.Context) (resObj *Win32LobAppFileSystemRule, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppFileSystemRule
func (r *Win32LobAppFileSystemRuleRequest) Update(ctx context.Context, reqObj *Win32LobAppFileSystemRule) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppFileSystemRule
func (r *Win32LobAppFileSystemRuleRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppInstallExperienceRequestBuilder is request builder for Win32LobAppInstallExperience
type Win32LobAppInstallExperienceRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppInstallExperienceRequest
func (b *Win32LobAppInstallExperienceRequestBuilder) Request() *Win32LobAppInstallExperienceRequest {
	return &Win32LobAppInstallExperienceRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppInstallExperienceRequest is request for Win32LobAppInstallExperience
type Win32LobAppInstallExperienceRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppInstallExperience
func (r *Win32LobAppInstallExperienceRequest) Get(ctx context.Context) (resObj *Win32LobAppInstallExperience, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppInstallExperience
func (r *Win32LobAppInstallExperienceRequest) Update(ctx context.Context, reqObj *Win32LobAppInstallExperience) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppInstallExperience
func (r *Win32LobAppInstallExperienceRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppMsiInformationRequestBuilder is request builder for Win32LobAppMsiInformation
type Win32LobAppMsiInformationRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppMsiInformationRequest
func (b *Win32LobAppMsiInformationRequestBuilder) Request() *Win32LobAppMsiInformationRequest {
	return &Win32LobAppMsiInformationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppMsiInformationRequest is request for Win32LobAppMsiInformation
type Win32LobAppMsiInformationRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppMsiInformation
func (r *Win32LobAppMsiInformationRequest) Get(ctx context.Context) (resObj *Win32LobAppMsiInformation, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppMsiInformation
func (r *Win32LobAppMsiInformationRequest) Update(ctx context.Context, reqObj *Win32LobAppMsiInformation) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppMsiInformation
func (r *Win32LobAppMsiInformationRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppPowerShellScriptDetectionRequestBuilder is request builder for Win32LobAppPowerShellScriptDetection
type Win32LobAppPowerShellScriptDetectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppPowerShellScriptDetectionRequest
func (b *Win32LobAppPowerShellScriptDetectionRequestBuilder) Request() *Win32LobAppPowerShellScriptDetectionRequest {
	return &Win32LobAppPowerShellScriptDetectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppPowerShellScriptDetectionRequest is request for Win32LobAppPowerShellScriptDetection
type Win32LobAppPowerShellScriptDetectionRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppPowerShellScriptDetection
func (r *Win32LobAppPowerShellScriptDetectionRequest) Get(ctx context.Context) (resObj *Win32LobAppPowerShellScriptDetection, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppPowerShellScriptDetection
func (r *Win32LobAppPowerShellScriptDetectionRequest) Update(ctx context.Context, reqObj *Win32LobAppPowerShellScriptDetection) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppPowerShellScriptDetection
func (r *Win32LobAppPowerShellScriptDetectionRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppPowerShellScriptRequirementRequestBuilder is request builder for Win32LobAppPowerShellScriptRequirement
type Win32LobAppPowerShellScriptRequirementRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppPowerShellScriptRequirementRequest
func (b *Win32LobAppPowerShellScriptRequirementRequestBuilder) Request() *Win32LobAppPowerShellScriptRequirementRequest {
	return &Win32LobAppPowerShellScriptRequirementRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppPowerShellScriptRequirementRequest is request for Win32LobAppPowerShellScriptRequirement
type Win32LobAppPowerShellScriptRequirementRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppPowerShellScriptRequirement
func (r *Win32LobAppPowerShellScriptRequirementRequest) Get(ctx context.Context) (resObj *Win32LobAppPowerShellScriptRequirement, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppPowerShellScriptRequirement
func (r *Win32LobAppPowerShellScriptRequirementRequest) Update(ctx context.Context, reqObj *Win32LobAppPowerShellScriptRequirement) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppPowerShellScriptRequirement
func (r *Win32LobAppPowerShellScriptRequirementRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppPowerShellScriptRuleRequestBuilder is request builder for Win32LobAppPowerShellScriptRule
type Win32LobAppPowerShellScriptRuleRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppPowerShellScriptRuleRequest
func (b *Win32LobAppPowerShellScriptRuleRequestBuilder) Request() *Win32LobAppPowerShellScriptRuleRequest {
	return &Win32LobAppPowerShellScriptRuleRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppPowerShellScriptRuleRequest is request for Win32LobAppPowerShellScriptRule
type Win32LobAppPowerShellScriptRuleRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppPowerShellScriptRule
func (r *Win32LobAppPowerShellScriptRuleRequest) Get(ctx context.Context) (resObj *Win32LobAppPowerShellScriptRule, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppPowerShellScriptRule
func (r *Win32LobAppPowerShellScriptRuleRequest) Update(ctx context.Context, reqObj *Win32LobAppPowerShellScriptRule) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppPowerShellScriptRule
func (r *Win32LobAppPowerShellScriptRuleRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppProductCodeDetectionRequestBuilder is request builder for Win32LobAppProductCodeDetection
type Win32LobAppProductCodeDetectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppProductCodeDetectionRequest
func (b *Win32LobAppProductCodeDetectionRequestBuilder) Request() *Win32LobAppProductCodeDetectionRequest {
	return &Win32LobAppProductCodeDetectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppProductCodeDetectionRequest is request for Win32LobAppProductCodeDetection
type Win32LobAppProductCodeDetectionRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppProductCodeDetection
func (r *Win32LobAppProductCodeDetectionRequest) Get(ctx context.Context) (resObj *Win32LobAppProductCodeDetection, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppProductCodeDetection
func (r *Win32LobAppProductCodeDetectionRequest) Update(ctx context.Context, reqObj *Win32LobAppProductCodeDetection) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppProductCodeDetection
func (r *Win32LobAppProductCodeDetectionRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppProductCodeRuleRequestBuilder is request builder for Win32LobAppProductCodeRule
type Win32LobAppProductCodeRuleRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppProductCodeRuleRequest
func (b *Win32LobAppProductCodeRuleRequestBuilder) Request() *Win32LobAppProductCodeRuleRequest {
	return &Win32LobAppProductCodeRuleRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppProductCodeRuleRequest is request for Win32LobAppProductCodeRule
type Win32LobAppProductCodeRuleRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppProductCodeRule
func (r *Win32LobAppProductCodeRuleRequest) Get(ctx context.Context) (resObj *Win32LobAppProductCodeRule, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppProductCodeRule
func (r *Win32LobAppProductCodeRuleRequest) Update(ctx context.Context, reqObj *Win32LobAppProductCodeRule) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppProductCodeRule
func (r *Win32LobAppProductCodeRuleRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppRegistryDetectionRequestBuilder is request builder for Win32LobAppRegistryDetection
type Win32LobAppRegistryDetectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppRegistryDetectionRequest
func (b *Win32LobAppRegistryDetectionRequestBuilder) Request() *Win32LobAppRegistryDetectionRequest {
	return &Win32LobAppRegistryDetectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppRegistryDetectionRequest is request for Win32LobAppRegistryDetection
type Win32LobAppRegistryDetectionRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppRegistryDetection
func (r *Win32LobAppRegistryDetectionRequest) Get(ctx context.Context) (resObj *Win32LobAppRegistryDetection, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppRegistryDetection
func (r *Win32LobAppRegistryDetectionRequest) Update(ctx context.Context, reqObj *Win32LobAppRegistryDetection) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppRegistryDetection
func (r *Win32LobAppRegistryDetectionRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppRegistryRequirementRequestBuilder is request builder for Win32LobAppRegistryRequirement
type Win32LobAppRegistryRequirementRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppRegistryRequirementRequest
func (b *Win32LobAppRegistryRequirementRequestBuilder) Request() *Win32LobAppRegistryRequirementRequest {
	return &Win32LobAppRegistryRequirementRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppRegistryRequirementRequest is request for Win32LobAppRegistryRequirement
type Win32LobAppRegistryRequirementRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppRegistryRequirement
func (r *Win32LobAppRegistryRequirementRequest) Get(ctx context.Context) (resObj *Win32LobAppRegistryRequirement, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppRegistryRequirement
func (r *Win32LobAppRegistryRequirementRequest) Update(ctx context.Context, reqObj *Win32LobAppRegistryRequirement) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppRegistryRequirement
func (r *Win32LobAppRegistryRequirementRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppRegistryRuleRequestBuilder is request builder for Win32LobAppRegistryRule
type Win32LobAppRegistryRuleRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppRegistryRuleRequest
func (b *Win32LobAppRegistryRuleRequestBuilder) Request() *Win32LobAppRegistryRuleRequest {
	return &Win32LobAppRegistryRuleRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppRegistryRuleRequest is request for Win32LobAppRegistryRule
type Win32LobAppRegistryRuleRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppRegistryRule
func (r *Win32LobAppRegistryRuleRequest) Get(ctx context.Context) (resObj *Win32LobAppRegistryRule, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppRegistryRule
func (r *Win32LobAppRegistryRuleRequest) Update(ctx context.Context, reqObj *Win32LobAppRegistryRule) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppRegistryRule
func (r *Win32LobAppRegistryRuleRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppRequirementRequestBuilder is request builder for Win32LobAppRequirement
type Win32LobAppRequirementRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppRequirementRequest
func (b *Win32LobAppRequirementRequestBuilder) Request() *Win32LobAppRequirementRequest {
	return &Win32LobAppRequirementRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppRequirementRequest is request for Win32LobAppRequirement
type Win32LobAppRequirementRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppRequirement
func (r *Win32LobAppRequirementRequest) Get(ctx context.Context) (resObj *Win32LobAppRequirement, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppRequirement
func (r *Win32LobAppRequirementRequest) Update(ctx context.Context, reqObj *Win32LobAppRequirement) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppRequirement
func (r *Win32LobAppRequirementRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppRestartSettingsRequestBuilder is request builder for Win32LobAppRestartSettings
type Win32LobAppRestartSettingsRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppRestartSettingsRequest
func (b *Win32LobAppRestartSettingsRequestBuilder) Request() *Win32LobAppRestartSettingsRequest {
	return &Win32LobAppRestartSettingsRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppRestartSettingsRequest is request for Win32LobAppRestartSettings
type Win32LobAppRestartSettingsRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppRestartSettings
func (r *Win32LobAppRestartSettingsRequest) Get(ctx context.Context) (resObj *Win32LobAppRestartSettings, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppRestartSettings
func (r *Win32LobAppRestartSettingsRequest) Update(ctx context.Context, reqObj *Win32LobAppRestartSettings) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppRestartSettings
func (r *Win32LobAppRestartSettingsRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppReturnCodeRequestBuilder is request builder for Win32LobAppReturnCode
type Win32LobAppReturnCodeRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppReturnCodeRequest
func (b *Win32LobAppReturnCodeRequestBuilder) Request() *Win32LobAppReturnCodeRequest {
	return &Win32LobAppReturnCodeRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppReturnCodeRequest is request for Win32LobAppReturnCode
type Win32LobAppReturnCodeRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppReturnCode
func (r *Win32LobAppReturnCodeRequest) Get(ctx context.Context) (resObj *Win32LobAppReturnCode, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppReturnCode
func (r *Win32LobAppReturnCodeRequest) Update(ctx context.Context, reqObj *Win32LobAppReturnCode) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppReturnCode
func (r *Win32LobAppReturnCodeRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// Win32LobAppRuleRequestBuilder is request builder for Win32LobAppRule
type Win32LobAppRuleRequestBuilder struct{ BaseRequestBuilder }

// Request returns Win32LobAppRuleRequest
func (b *Win32LobAppRuleRequestBuilder) Request() *Win32LobAppRuleRequest {
	return &Win32LobAppRuleRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// Win32LobAppRuleRequest is request for Win32LobAppRule
type Win32LobAppRuleRequest struct{ BaseRequest }

// Get performs GET request for Win32LobAppRule
func (r *Win32LobAppRuleRequest) Get(ctx context.Context) (resObj *Win32LobAppRule, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Win32LobAppRule
func (r *Win32LobAppRuleRequest) Update(ctx context.Context, reqObj *Win32LobAppRule) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Win32LobAppRule
func (r *Win32LobAppRuleRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
