// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// InvestigationSecurityStateRequestBuilder is request builder for InvestigationSecurityState
type InvestigationSecurityStateRequestBuilder struct{ BaseRequestBuilder }

// Request returns InvestigationSecurityStateRequest
func (b *InvestigationSecurityStateRequestBuilder) Request() *InvestigationSecurityStateRequest {
	return &InvestigationSecurityStateRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// InvestigationSecurityStateRequest is request for InvestigationSecurityState
type InvestigationSecurityStateRequest struct{ BaseRequest }

// Get performs GET request for InvestigationSecurityState
func (r *InvestigationSecurityStateRequest) Get(ctx context.Context) (resObj *InvestigationSecurityState, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for InvestigationSecurityState
func (r *InvestigationSecurityStateRequest) Update(ctx context.Context, reqObj *InvestigationSecurityState) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for InvestigationSecurityState
func (r *InvestigationSecurityStateRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
