// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// ExtractSensitivityLabelsResultRequestBuilder is request builder for ExtractSensitivityLabelsResult
type ExtractSensitivityLabelsResultRequestBuilder struct{ BaseRequestBuilder }

// Request returns ExtractSensitivityLabelsResultRequest
func (b *ExtractSensitivityLabelsResultRequestBuilder) Request() *ExtractSensitivityLabelsResultRequest {
	return &ExtractSensitivityLabelsResultRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ExtractSensitivityLabelsResultRequest is request for ExtractSensitivityLabelsResult
type ExtractSensitivityLabelsResultRequest struct{ BaseRequest }

// Get performs GET request for ExtractSensitivityLabelsResult
func (r *ExtractSensitivityLabelsResultRequest) Get(ctx context.Context) (resObj *ExtractSensitivityLabelsResult, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for ExtractSensitivityLabelsResult
func (r *ExtractSensitivityLabelsResultRequest) Update(ctx context.Context, reqObj *ExtractSensitivityLabelsResult) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for ExtractSensitivityLabelsResult
func (r *ExtractSensitivityLabelsResultRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
