// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// ManagementCertificateWithThumbprintRequestBuilder is request builder for ManagementCertificateWithThumbprint
type ManagementCertificateWithThumbprintRequestBuilder struct{ BaseRequestBuilder }

// Request returns ManagementCertificateWithThumbprintRequest
func (b *ManagementCertificateWithThumbprintRequestBuilder) Request() *ManagementCertificateWithThumbprintRequest {
	return &ManagementCertificateWithThumbprintRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ManagementCertificateWithThumbprintRequest is request for ManagementCertificateWithThumbprint
type ManagementCertificateWithThumbprintRequest struct{ BaseRequest }

// Get performs GET request for ManagementCertificateWithThumbprint
func (r *ManagementCertificateWithThumbprintRequest) Get(ctx context.Context) (resObj *ManagementCertificateWithThumbprint, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for ManagementCertificateWithThumbprint
func (r *ManagementCertificateWithThumbprintRequest) Update(ctx context.Context, reqObj *ManagementCertificateWithThumbprint) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for ManagementCertificateWithThumbprint
func (r *ManagementCertificateWithThumbprintRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
