// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// PhysicalAddressRequestBuilder is request builder for PhysicalAddress
type PhysicalAddressRequestBuilder struct{ BaseRequestBuilder }

// Request returns PhysicalAddressRequest
func (b *PhysicalAddressRequestBuilder) Request() *PhysicalAddressRequest {
	return &PhysicalAddressRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// PhysicalAddressRequest is request for PhysicalAddress
type PhysicalAddressRequest struct{ BaseRequest }

// Get performs GET request for PhysicalAddress
func (r *PhysicalAddressRequest) Get(ctx context.Context) (resObj *PhysicalAddress, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for PhysicalAddress
func (r *PhysicalAddressRequest) Update(ctx context.Context, reqObj *PhysicalAddress) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for PhysicalAddress
func (r *PhysicalAddressRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// PhysicalOfficeAddressRequestBuilder is request builder for PhysicalOfficeAddress
type PhysicalOfficeAddressRequestBuilder struct{ BaseRequestBuilder }

// Request returns PhysicalOfficeAddressRequest
func (b *PhysicalOfficeAddressRequestBuilder) Request() *PhysicalOfficeAddressRequest {
	return &PhysicalOfficeAddressRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// PhysicalOfficeAddressRequest is request for PhysicalOfficeAddress
type PhysicalOfficeAddressRequest struct{ BaseRequest }

// Get performs GET request for PhysicalOfficeAddress
func (r *PhysicalOfficeAddressRequest) Get(ctx context.Context) (resObj *PhysicalOfficeAddress, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for PhysicalOfficeAddress
func (r *PhysicalOfficeAddressRequest) Update(ctx context.Context, reqObj *PhysicalOfficeAddress) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for PhysicalOfficeAddress
func (r *PhysicalOfficeAddressRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
