// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// StaleSignInAlertConfigurationRequestBuilder is request builder for StaleSignInAlertConfiguration
type StaleSignInAlertConfigurationRequestBuilder struct{ BaseRequestBuilder }

// Request returns StaleSignInAlertConfigurationRequest
func (b *StaleSignInAlertConfigurationRequestBuilder) Request() *StaleSignInAlertConfigurationRequest {
	return &StaleSignInAlertConfigurationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// StaleSignInAlertConfigurationRequest is request for StaleSignInAlertConfiguration
type StaleSignInAlertConfigurationRequest struct{ BaseRequest }

// Get performs GET request for StaleSignInAlertConfiguration
func (r *StaleSignInAlertConfigurationRequest) Get(ctx context.Context) (resObj *StaleSignInAlertConfiguration, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for StaleSignInAlertConfiguration
func (r *StaleSignInAlertConfigurationRequest) Update(ctx context.Context, reqObj *StaleSignInAlertConfiguration) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for StaleSignInAlertConfiguration
func (r *StaleSignInAlertConfigurationRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// StaleSignInAlertIncidentRequestBuilder is request builder for StaleSignInAlertIncident
type StaleSignInAlertIncidentRequestBuilder struct{ BaseRequestBuilder }

// Request returns StaleSignInAlertIncidentRequest
func (b *StaleSignInAlertIncidentRequestBuilder) Request() *StaleSignInAlertIncidentRequest {
	return &StaleSignInAlertIncidentRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// StaleSignInAlertIncidentRequest is request for StaleSignInAlertIncident
type StaleSignInAlertIncidentRequest struct{ BaseRequest }

// Get performs GET request for StaleSignInAlertIncident
func (r *StaleSignInAlertIncidentRequest) Get(ctx context.Context) (resObj *StaleSignInAlertIncident, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for StaleSignInAlertIncident
func (r *StaleSignInAlertIncidentRequest) Update(ctx context.Context, reqObj *StaleSignInAlertIncident) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for StaleSignInAlertIncident
func (r *StaleSignInAlertIncidentRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
