// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// StringKeyAttributeMappingSourceValuePairRequestBuilder is request builder for StringKeyAttributeMappingSourceValuePair
type StringKeyAttributeMappingSourceValuePairRequestBuilder struct{ BaseRequestBuilder }

// Request returns StringKeyAttributeMappingSourceValuePairRequest
func (b *StringKeyAttributeMappingSourceValuePairRequestBuilder) Request() *StringKeyAttributeMappingSourceValuePairRequest {
	return &StringKeyAttributeMappingSourceValuePairRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// StringKeyAttributeMappingSourceValuePairRequest is request for StringKeyAttributeMappingSourceValuePair
type StringKeyAttributeMappingSourceValuePairRequest struct{ BaseRequest }

// Get performs GET request for StringKeyAttributeMappingSourceValuePair
func (r *StringKeyAttributeMappingSourceValuePairRequest) Get(ctx context.Context) (resObj *StringKeyAttributeMappingSourceValuePair, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for StringKeyAttributeMappingSourceValuePair
func (r *StringKeyAttributeMappingSourceValuePairRequest) Update(ctx context.Context, reqObj *StringKeyAttributeMappingSourceValuePair) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for StringKeyAttributeMappingSourceValuePair
func (r *StringKeyAttributeMappingSourceValuePairRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// StringKeyLongValuePairRequestBuilder is request builder for StringKeyLongValuePair
type StringKeyLongValuePairRequestBuilder struct{ BaseRequestBuilder }

// Request returns StringKeyLongValuePairRequest
func (b *StringKeyLongValuePairRequestBuilder) Request() *StringKeyLongValuePairRequest {
	return &StringKeyLongValuePairRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// StringKeyLongValuePairRequest is request for StringKeyLongValuePair
type StringKeyLongValuePairRequest struct{ BaseRequest }

// Get performs GET request for StringKeyLongValuePair
func (r *StringKeyLongValuePairRequest) Get(ctx context.Context) (resObj *StringKeyLongValuePair, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for StringKeyLongValuePair
func (r *StringKeyLongValuePairRequest) Update(ctx context.Context, reqObj *StringKeyLongValuePair) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for StringKeyLongValuePair
func (r *StringKeyLongValuePairRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// StringKeyObjectValuePairRequestBuilder is request builder for StringKeyObjectValuePair
type StringKeyObjectValuePairRequestBuilder struct{ BaseRequestBuilder }

// Request returns StringKeyObjectValuePairRequest
func (b *StringKeyObjectValuePairRequestBuilder) Request() *StringKeyObjectValuePairRequest {
	return &StringKeyObjectValuePairRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// StringKeyObjectValuePairRequest is request for StringKeyObjectValuePair
type StringKeyObjectValuePairRequest struct{ BaseRequest }

// Get performs GET request for StringKeyObjectValuePair
func (r *StringKeyObjectValuePairRequest) Get(ctx context.Context) (resObj *StringKeyObjectValuePair, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for StringKeyObjectValuePair
func (r *StringKeyObjectValuePairRequest) Update(ctx context.Context, reqObj *StringKeyObjectValuePair) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for StringKeyObjectValuePair
func (r *StringKeyObjectValuePairRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// StringKeyStringValuePairRequestBuilder is request builder for StringKeyStringValuePair
type StringKeyStringValuePairRequestBuilder struct{ BaseRequestBuilder }

// Request returns StringKeyStringValuePairRequest
func (b *StringKeyStringValuePairRequestBuilder) Request() *StringKeyStringValuePairRequest {
	return &StringKeyStringValuePairRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// StringKeyStringValuePairRequest is request for StringKeyStringValuePair
type StringKeyStringValuePairRequest struct{ BaseRequest }

// Get performs GET request for StringKeyStringValuePair
func (r *StringKeyStringValuePairRequest) Get(ctx context.Context) (resObj *StringKeyStringValuePair, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for StringKeyStringValuePair
func (r *StringKeyStringValuePairRequest) Update(ctx context.Context, reqObj *StringKeyStringValuePair) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for StringKeyStringValuePair
func (r *StringKeyStringValuePairRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
