// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// ParameterRequestBuilder is request builder for Parameter
type ParameterRequestBuilder struct{ BaseRequestBuilder }

// Request returns ParameterRequest
func (b *ParameterRequestBuilder) Request() *ParameterRequest {
	return &ParameterRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ParameterRequest is request for Parameter
type ParameterRequest struct{ BaseRequest }

// Get performs GET request for Parameter
func (r *ParameterRequest) Get(ctx context.Context) (resObj *Parameter, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Parameter
func (r *ParameterRequest) Update(ctx context.Context, reqObj *Parameter) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Parameter
func (r *ParameterRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
