// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequestBuilder is request builder for RolesAssignedOutsidePrivilegedIdentityManagementAlertConfiguration
type RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequestBuilder struct{ BaseRequestBuilder }

// Request returns RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequest
func (b *RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequestBuilder) Request() *RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequest {
	return &RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequest is request for RolesAssignedOutsidePrivilegedIdentityManagementAlertConfiguration
type RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequest struct{ BaseRequest }

// Get performs GET request for RolesAssignedOutsidePrivilegedIdentityManagementAlertConfiguration
func (r *RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequest) Get(ctx context.Context) (resObj *RolesAssignedOutsidePrivilegedIdentityManagementAlertConfiguration, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for RolesAssignedOutsidePrivilegedIdentityManagementAlertConfiguration
func (r *RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequest) Update(ctx context.Context, reqObj *RolesAssignedOutsidePrivilegedIdentityManagementAlertConfiguration) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for RolesAssignedOutsidePrivilegedIdentityManagementAlertConfiguration
func (r *RolesAssignedOutsidePrivilegedIdentityManagementAlertConfigurationRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequestBuilder is request builder for RolesAssignedOutsidePrivilegedIdentityManagementAlertIncident
type RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequestBuilder struct{ BaseRequestBuilder }

// Request returns RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequest
func (b *RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequestBuilder) Request() *RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequest {
	return &RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequest is request for RolesAssignedOutsidePrivilegedIdentityManagementAlertIncident
type RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequest struct{ BaseRequest }

// Get performs GET request for RolesAssignedOutsidePrivilegedIdentityManagementAlertIncident
func (r *RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequest) Get(ctx context.Context) (resObj *RolesAssignedOutsidePrivilegedIdentityManagementAlertIncident, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for RolesAssignedOutsidePrivilegedIdentityManagementAlertIncident
func (r *RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequest) Update(ctx context.Context, reqObj *RolesAssignedOutsidePrivilegedIdentityManagementAlertIncident) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for RolesAssignedOutsidePrivilegedIdentityManagementAlertIncident
func (r *RolesAssignedOutsidePrivilegedIdentityManagementAlertIncidentRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
